//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.26 at 04:34:25 PM PDT 
//

package org.hl7.vmr.r2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

/**
 * A denial of the existence of a condition, problem, or allergy.
 * 
 * <p>
 * Java class for AbstractDeniedCondition complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="AbstractDeniedCondition">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:hl7-org:vmr:r2}ConditionBase">
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractDeniedCondition")
@XmlSeeAlso({
    DeniedAllergyOrIntolerance.class, NoKnownAllergy.class, DeniedProblem.class
})
public abstract class AbstractDeniedCondition extends ConditionBase {

}
