//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.30 at 06:15:10 PM PDT 
//


package org.hl7.vmr.r2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import org.hl7.cdsdt.r2.BL;
import org.hl7.cdsdt.r2.CD;
import org.hl7.cdsdt.r2.PQ;


/**
 * An assertion regarding a clinical condition of the subject that needs to be treated or managed.
 * 
 * <p>Java class for AbstractCondition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AbstractCondition">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:hl7-org:vmr:r2}ConditionBase">
 *       &lt;sequence>
 *         &lt;element name="ageAtOnset" type="{urn:hl7-org:cdsdt:r2}PQ" minOccurs="0"/>
 *         &lt;element name="certainty" type="{urn:hl7-org:cdsdt:r2}CD" minOccurs="0"/>
 *         &lt;element name="conditionStatus" type="{urn:hl7-org:cdsdt:r2}CD" minOccurs="0"/>
 *         &lt;element name="contributedToDeath" type="{urn:hl7-org:cdsdt:r2}BL" minOccurs="0"/>
 *         &lt;element name="wasCauseOfDeath" type="{urn:hl7-org:cdsdt:r2}BL" minOccurs="0"/>
 *         &lt;element name="criticality" type="{urn:hl7-org:cdsdt:r2}CD" minOccurs="0"/>
 *         &lt;element name="severity" type="{urn:hl7-org:cdsdt:r2}CD" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractCondition", propOrder = {
    "ageAtOnset",
    "certainty",
    "conditionStatus",
    "contributedToDeath",
    "wasCauseOfDeath",
    "criticality",
    "severity"
})
@XmlSeeAlso({
    AllergyOrIntolerance.class,
    Problem.class
})
public abstract class AbstractCondition
    extends ConditionBase
{

    protected PQ ageAtOnset;
    protected CD certainty;
    protected CD conditionStatus;
    protected BL contributedToDeath;
    protected BL wasCauseOfDeath;
    protected CD criticality;
    protected CD severity;

    /**
     * Gets the value of the ageAtOnset property.
     * 
     * @return
     *     possible object is
     *     {@link PQ }
     *     
     */
    public PQ getAgeAtOnset() {
        return ageAtOnset;
    }

    /**
     * Sets the value of the ageAtOnset property.
     * 
     * @param value
     *     allowed object is
     *     {@link PQ }
     *     
     */
    public void setAgeAtOnset(PQ value) {
        this.ageAtOnset = value;
    }

    /**
     * Gets the value of the certainty property.
     * 
     * @return
     *     possible object is
     *     {@link CD }
     *     
     */
    public CD getCertainty() {
        return certainty;
    }

    /**
     * Sets the value of the certainty property.
     * 
     * @param value
     *     allowed object is
     *     {@link CD }
     *     
     */
    public void setCertainty(CD value) {
        this.certainty = value;
    }

    /**
     * Gets the value of the conditionStatus property.
     * 
     * @return
     *     possible object is
     *     {@link CD }
     *     
     */
    public CD getConditionStatus() {
        return conditionStatus;
    }

    /**
     * Sets the value of the conditionStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link CD }
     *     
     */
    public void setConditionStatus(CD value) {
        this.conditionStatus = value;
    }

    /**
     * Gets the value of the contributedToDeath property.
     * 
     * @return
     *     possible object is
     *     {@link BL }
     *     
     */
    public BL getContributedToDeath() {
        return contributedToDeath;
    }

    /**
     * Sets the value of the contributedToDeath property.
     * 
     * @param value
     *     allowed object is
     *     {@link BL }
     *     
     */
    public void setContributedToDeath(BL value) {
        this.contributedToDeath = value;
    }

    /**
     * Gets the value of the wasCauseOfDeath property.
     * 
     * @return
     *     possible object is
     *     {@link BL }
     *     
     */
    public BL getWasCauseOfDeath() {
        return wasCauseOfDeath;
    }

    /**
     * Sets the value of the wasCauseOfDeath property.
     * 
     * @param value
     *     allowed object is
     *     {@link BL }
     *     
     */
    public void setWasCauseOfDeath(BL value) {
        this.wasCauseOfDeath = value;
    }

    /**
     * Gets the value of the criticality property.
     * 
     * @return
     *     possible object is
     *     {@link CD }
     *     
     */
    public CD getCriticality() {
        return criticality;
    }

    /**
     * Sets the value of the criticality property.
     * 
     * @param value
     *     allowed object is
     *     {@link CD }
     *     
     */
    public void setCriticality(CD value) {
        this.criticality = value;
    }

    /**
     * Gets the value of the severity property.
     * 
     * @return
     *     possible object is
     *     {@link CD }
     *     
     */
    public CD getSeverity() {
        return severity;
    }

    /**
     * Sets the value of the severity property.
     * 
     * @param value
     *     allowed object is
     *     {@link CD }
     *     
     */
    public void setSeverity(CD value) {
        this.severity = value;
    }

}
