//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.30 at 06:15:10 PM PDT 
//


package org.hl7.vmr.r2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.hl7.cdsdt.r2.CD;
import org.hl7.cdsdt.r2.RTO;
import org.hl7.cdsdt.r2.ST;
import org.hl7.cdsdt.r2.TS;


/**
 * A material, generally but not exclusively a medication or antigen, of a particular constitution that can be given to a person to enable a clinical effect.  An administrable substance may have component administrable substances.
 * 
 * <p>Java class for AdministrableSubstance complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AdministrableSubstance">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:hl7-org:vmr:r2}Entity">
 *       &lt;sequence>
 *         &lt;element name="substanceCode" type="{urn:hl7-org:cdsdt:r2}CD"/>
 *         &lt;element name="substanceBrandCode" type="{urn:hl7-org:cdsdt:r2}CD" minOccurs="0"/>
 *         &lt;element name="substanceGenericCode" type="{urn:hl7-org:cdsdt:r2}CD" minOccurs="0"/>
 *         &lt;element name="manufacturer" type="{urn:hl7-org:cdsdt:r2}CD" minOccurs="0"/>
 *         &lt;element name="strength" type="{urn:hl7-org:cdsdt:r2}RTO" minOccurs="0"/>
 *         &lt;element name="form" type="{urn:hl7-org:cdsdt:r2}CD" minOccurs="0"/>
 *         &lt;element name="expirationDate" type="{urn:hl7-org:cdsdt:r2}TS" minOccurs="0"/>
 *         &lt;element name="vaccinationProtocol" type="{urn:hl7-org:vmr:r2}VaccinationProtocol" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="lotNumber" type="{urn:hl7-org:cdsdt:r2}ST" minOccurs="0"/>
 *         &lt;element name="ingredient" type="{urn:hl7-org:vmr:r2}AdministrableSubstance" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AdministrableSubstance", propOrder = {
    "substanceCode",
    "substanceBrandCode",
    "substanceGenericCode",
    "manufacturer",
    "strength",
    "form",
    "expirationDate",
    "vaccinationProtocol",
    "lotNumber",
    "ingredient"
})
public class AdministrableSubstance
    extends Entity
{

    @XmlElement(required = true)
    protected CD substanceCode;
    protected CD substanceBrandCode;
    protected CD substanceGenericCode;
    protected CD manufacturer;
    protected RTO strength;
    protected CD form;
    protected TS expirationDate;
    protected List<VaccinationProtocol> vaccinationProtocol;
    protected ST lotNumber;
    protected List<AdministrableSubstance> ingredient;

    /**
     * Gets the value of the substanceCode property.
     * 
     * @return
     *     possible object is
     *     {@link CD }
     *     
     */
    public CD getSubstanceCode() {
        return substanceCode;
    }

    /**
     * Sets the value of the substanceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CD }
     *     
     */
    public void setSubstanceCode(CD value) {
        this.substanceCode = value;
    }

    /**
     * Gets the value of the substanceBrandCode property.
     * 
     * @return
     *     possible object is
     *     {@link CD }
     *     
     */
    public CD getSubstanceBrandCode() {
        return substanceBrandCode;
    }

    /**
     * Sets the value of the substanceBrandCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CD }
     *     
     */
    public void setSubstanceBrandCode(CD value) {
        this.substanceBrandCode = value;
    }

    /**
     * Gets the value of the substanceGenericCode property.
     * 
     * @return
     *     possible object is
     *     {@link CD }
     *     
     */
    public CD getSubstanceGenericCode() {
        return substanceGenericCode;
    }

    /**
     * Sets the value of the substanceGenericCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CD }
     *     
     */
    public void setSubstanceGenericCode(CD value) {
        this.substanceGenericCode = value;
    }

    /**
     * Gets the value of the manufacturer property.
     * 
     * @return
     *     possible object is
     *     {@link CD }
     *     
     */
    public CD getManufacturer() {
        return manufacturer;
    }

    /**
     * Sets the value of the manufacturer property.
     * 
     * @param value
     *     allowed object is
     *     {@link CD }
     *     
     */
    public void setManufacturer(CD value) {
        this.manufacturer = value;
    }

    /**
     * Gets the value of the strength property.
     * 
     * @return
     *     possible object is
     *     {@link RTO }
     *     
     */
    public RTO getStrength() {
        return strength;
    }

    /**
     * Sets the value of the strength property.
     * 
     * @param value
     *     allowed object is
     *     {@link RTO }
     *     
     */
    public void setStrength(RTO value) {
        this.strength = value;
    }

    /**
     * Gets the value of the form property.
     * 
     * @return
     *     possible object is
     *     {@link CD }
     *     
     */
    public CD getForm() {
        return form;
    }

    /**
     * Sets the value of the form property.
     * 
     * @param value
     *     allowed object is
     *     {@link CD }
     *     
     */
    public void setForm(CD value) {
        this.form = value;
    }

    /**
     * Gets the value of the expirationDate property.
     * 
     * @return
     *     possible object is
     *     {@link TS }
     *     
     */
    public TS getExpirationDate() {
        return expirationDate;
    }

    /**
     * Sets the value of the expirationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link TS }
     *     
     */
    public void setExpirationDate(TS value) {
        this.expirationDate = value;
    }

    /**
     * Gets the value of the vaccinationProtocol property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the vaccinationProtocol property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVaccinationProtocol().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VaccinationProtocol }
     * 
     * 
     */
    public List<VaccinationProtocol> getVaccinationProtocol() {
        if (vaccinationProtocol == null) {
            vaccinationProtocol = new ArrayList<VaccinationProtocol>();
        }
        return this.vaccinationProtocol;
    }

    /**
     * Gets the value of the lotNumber property.
     * 
     * @return
     *     possible object is
     *     {@link ST }
     *     
     */
    public ST getLotNumber() {
        return lotNumber;
    }

    /**
     * Sets the value of the lotNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link ST }
     *     
     */
    public void setLotNumber(ST value) {
        this.lotNumber = value;
    }

    /**
     * Gets the value of the ingredient property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ingredient property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIngredient().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdministrableSubstance }
     * 
     * 
     */
    public List<AdministrableSubstance> getIngredient() {
        if (ingredient == null) {
            ingredient = new ArrayList<AdministrableSubstance>();
        }
        return this.ingredient;
    }

}
