//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.30 at 06:15:10 PM PDT 
//


package org.hl7.vmr.r2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import org.hl7.cdsdt.r2.CD;


/**
 * An allergy or intolerance triggered by a known or suspected agent. Note that one class is used to represent both concepts as it is often difficult to distinguish the two.
 * 
 * <p>Java class for AllergyOrIntolerance complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AllergyOrIntolerance">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:hl7-org:vmr:r2}AbstractCondition">
 *       &lt;sequence>
 *         &lt;element name="agent" type="{urn:hl7-org:cdsdt:r2}CD" minOccurs="0"/>
 *         &lt;element name="associatedReactionType" type="{urn:hl7-org:cdsdt:r2}CD" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AllergyOrIntolerance", propOrder = {
    "agent",
    "associatedReactionType"
})
public class AllergyOrIntolerance
    extends AbstractCondition
{

    protected CD agent;
    protected List<CD> associatedReactionType;

    /**
     * Gets the value of the agent property.
     * 
     * @return
     *     possible object is
     *     {@link CD }
     *     
     */
    public CD getAgent() {
        return agent;
    }

    /**
     * Sets the value of the agent property.
     * 
     * @param value
     *     allowed object is
     *     {@link CD }
     *     
     */
    public void setAgent(CD value) {
        this.agent = value;
    }

    /**
     * Gets the value of the associatedReactionType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the associatedReactionType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAssociatedReactionType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CD }
     * 
     * 
     */
    public List<CD> getAssociatedReactionType() {
        if (associatedReactionType == null) {
            associatedReactionType = new ArrayList<CD>();
        }
        return this.associatedReactionType;
    }

}
