//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.26 at 04:34:25 PM PDT 
//

package org.hl7.vmr.r2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.hl7.cdsdt.r2.INT;
import org.hl7.cdsdt.r2.IVLPQ;

/**
 * A class representing an order for a composite medication such as IV fluid
 * that may consist of one or more additives mixed into a diluent. Additives and
 * diluents are represented as constituents with the appropriate
 * constituentType.
 * 
 * <p>
 * Java class for CompositeSubstanceOrder complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="CompositeSubstanceOrder">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:hl7-org:vmr:r2}SubstanceAdministrationOrder">
 *       &lt;sequence>
 *         &lt;element name="constituent" type="{urn:hl7-org:vmr:r2}Constituent" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="totalVolume" type="{urn:hl7-org:cdsdt:r2}IVL_PQ" minOccurs="0"/>
 *         &lt;element name="pH" type="{urn:hl7-org:cdsdt:r2}INT" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CompositeSubstanceOrder", propOrder = {
    "constituent", "totalVolume", "ph"
})
public class CompositeSubstanceOrder extends SubstanceAdministrationOrder {

  protected List<Constituent> constituent;

  protected IVLPQ totalVolume;

  @XmlElement(name = "pH")
  protected INT ph;

  /**
   * Gets the value of the constituent property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot.
   * Therefore any modification you make to the returned list will be present
   * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
   * for the constituent property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
   * getConstituent().add(newItem);
   * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link Constituent }
   * 
   * 
   */
  public List<Constituent> getConstituent() {
    if (constituent == null) {
      constituent = new ArrayList<Constituent>();
    }
    return this.constituent;
  }

  /**
   * Gets the value of the totalVolume property.
   * 
   * @return possible object is {@link IVLPQ }
   * 
   */
  public IVLPQ getTotalVolume() {
    return totalVolume;
  }

  /**
   * Sets the value of the totalVolume property.
   * 
   * @param value allowed object is {@link IVLPQ }
   * 
   */
  public void setTotalVolume(IVLPQ value) {
    this.totalVolume = value;
  }

  /**
   * Gets the value of the ph property.
   * 
   * @return possible object is {@link INT }
   * 
   */
  public INT getPH() {
    return ph;
  }

  /**
   * Sets the value of the ph property.
   * 
   * @param value allowed object is {@link INT }
   * 
   */
  public void setPH(INT value) {
    this.ph = value;
  }

}
