//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.30 at 06:15:10 PM PDT 
//


package org.hl7.vmr.r2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import org.hl7.cdsdt.r2.CD;
import org.hl7.cdsdt.r2.IVLTS;


/**
 * Abstract base class for problems, which are clinical conditions that need to be treated or managed.
 * 
 * Note that allergies are represented as a special type of conditions represented by the AllergyOrIntolerance concept, whereas individual adverse events are represented as adverse events.
 * 
 * <p>Java class for ConditionBase complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConditionBase">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:hl7-org:vmr:r2}ClinicalStatement">
 *       &lt;sequence>
 *         &lt;element name="affectedBodySite" type="{urn:hl7-org:vmr:r2}BodySite" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="conditionCode" type="{urn:hl7-org:cdsdt:r2}CD"/>
 *         &lt;element name="conditionEffectiveTime" type="{urn:hl7-org:cdsdt:r2}IVL_TS" minOccurs="0"/>
 *         &lt;element name="diagnosticEventTime" type="{urn:hl7-org:cdsdt:r2}IVL_TS" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConditionBase", propOrder = {
    "affectedBodySite",
    "conditionCode",
    "conditionEffectiveTime",
    "diagnosticEventTime"
})
@XmlSeeAlso({
    AbstractDeniedCondition.class,
    AbstractCondition.class
})
public abstract class ConditionBase
    extends ClinicalStatement
{

    protected List<BodySite> affectedBodySite;
    @XmlElement(required = true)
    protected CD conditionCode;
    protected IVLTS conditionEffectiveTime;
    protected IVLTS diagnosticEventTime;

    /**
     * Gets the value of the affectedBodySite property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the affectedBodySite property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAffectedBodySite().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BodySite }
     * 
     * 
     */
    public List<BodySite> getAffectedBodySite() {
        if (affectedBodySite == null) {
            affectedBodySite = new ArrayList<BodySite>();
        }
        return this.affectedBodySite;
    }

    /**
     * Gets the value of the conditionCode property.
     * 
     * @return
     *     possible object is
     *     {@link CD }
     *     
     */
    public CD getConditionCode() {
        return conditionCode;
    }

    /**
     * Sets the value of the conditionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CD }
     *     
     */
    public void setConditionCode(CD value) {
        this.conditionCode = value;
    }

    /**
     * Gets the value of the conditionEffectiveTime property.
     * 
     * @return
     *     possible object is
     *     {@link IVLTS }
     *     
     */
    public IVLTS getConditionEffectiveTime() {
        return conditionEffectiveTime;
    }

    /**
     * Sets the value of the conditionEffectiveTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link IVLTS }
     *     
     */
    public void setConditionEffectiveTime(IVLTS value) {
        this.conditionEffectiveTime = value;
    }

    /**
     * Gets the value of the diagnosticEventTime property.
     * 
     * @return
     *     possible object is
     *     {@link IVLTS }
     *     
     */
    public IVLTS getDiagnosticEventTime() {
        return diagnosticEventTime;
    }

    /**
     * Sets the value of the diagnosticEventTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link IVLTS }
     *     
     */
    public void setDiagnosticEventTime(IVLTS value) {
        this.diagnosticEventTime = value;
    }

}
