//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.26 at 04:34:25 PM PDT 
//

package org.hl7.vmr.r2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * A denial that the subject has or had the specified adverse event. E.g., if
 * adverseEventCode is hives, adverse event agent is penicillin, and
 * documentation time is 2011-05-01, an assertion was made on 2011-05-01 that
 * the subject does not get hives as a reaction to penicillin.
 * 
 * <p>
 * Java class for DeniedAdverseEvent complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="DeniedAdverseEvent">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:hl7-org:vmr:r2}AdverseEventBase">
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DeniedAdverseEvent")
public class DeniedAdverseEvent extends AdverseEventBase {

}
