//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.30 at 06:15:10 PM PDT 
//


package org.hl7.vmr.r2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import org.hl7.cdsdt.r2.CD;


/**
 * An statement denying the presence of an allergy or intolerance to a specific agent.
 * 
 * <p>Java class for DeniedAllergyOrIntolerance complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DeniedAllergyOrIntolerance">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:hl7-org:vmr:r2}AbstractDeniedCondition">
 *       &lt;sequence>
 *         &lt;element name="agent" type="{urn:hl7-org:cdsdt:r2}CD" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DeniedAllergyOrIntolerance", propOrder = {
    "agent"
})
public class DeniedAllergyOrIntolerance
    extends AbstractDeniedCondition
{

    protected CD agent;

    /**
     * Gets the value of the agent property.
     * 
     * @return
     *     possible object is
     *     {@link CD }
     *     
     */
    public CD getAgent() {
        return agent;
    }

    /**
     * Sets the value of the agent property.
     * 
     * @param value
     *     allowed object is
     *     {@link CD }
     *     
     */
    public void setAgent(CD value) {
        this.agent = value;
    }

}
