//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.26 at 04:34:25 PM PDT 
//

package org.hl7.vmr.r2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import org.hl7.cdsdt.r2.CD;
import org.hl7.cdsdt.r2.IVLPQ;
import org.hl7.cdsdt.r2.PQ;
import org.hl7.cdsdt.r2.ST;

/**
 * How the medication is to be used by or administered to the patient.
 * 
 * <p>
 * Java class for Dose complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Dose">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:hl7-org:vmr:r2}ExtendedVmrTypeBase">
 *       &lt;sequence>
 *         &lt;element name="dosageInstructionText" type="{urn:hl7-org:cdsdt:r2}ST" minOccurs="0"/>
 *         &lt;element name="additionalInstructions" type="{urn:hl7-org:cdsdt:r2}CD" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="doseType" type="{urn:hl7-org:cdsdt:r2}CD" minOccurs="0"/>
 *         &lt;element name="doseQuantity" type="{urn:hl7-org:cdsdt:r2}IVL_PQ" minOccurs="0"/>
 *         &lt;element name="doseRestriction" type="{urn:hl7-org:vmr:r2}DoseRestriction" minOccurs="0"/>
 *         &lt;element name="doseGoal" type="{urn:hl7-org:vmr:r2}DoseRestriction" minOccurs="0"/>
 *         &lt;element name="approachBodySite" type="{urn:hl7-org:vmr:r2}BodySite" minOccurs="0"/>
 *         &lt;element name="targetBodySite" type="{urn:hl7-org:vmr:r2}BodySite" minOccurs="0"/>
 *         &lt;element name="deliveryRoute" type="{urn:hl7-org:cdsdt:r2}CD" minOccurs="0"/>
 *         &lt;element name="deliveryMethod" type="{urn:hl7-org:cdsdt:r2}CD" minOccurs="0"/>
 *         &lt;element name="deliveryRate" type="{urn:hl7-org:cdsdt:r2}IVL_PQ" minOccurs="0"/>
 *         &lt;element name="deliveryRateIncrement" type="{urn:hl7-org:cdsdt:r2}IVL_PQ" minOccurs="0"/>
 *         &lt;element name="deliveryRateIncrementInterval" type="{urn:hl7-org:cdsdt:r2}IVL_PQ" minOccurs="0"/>
 *         &lt;element name="deliveryRateGoal" type="{urn:hl7-org:cdsdt:r2}IVL_PQ" minOccurs="0"/>
 *         &lt;element name="infuseOver" type="{urn:hl7-org:cdsdt:r2}PQ" minOccurs="0"/>
 *         &lt;element name="maximumDeliveryRate" type="{urn:hl7-org:cdsdt:r2}PQ" minOccurs="0"/>
 *         &lt;element name="maximumDeliveredVolume" type="{urn:hl7-org:cdsdt:r2}PQ" minOccurs="0"/>
 *         &lt;element name="frequency" type="{urn:hl7-org:vmr:r2}Schedule" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Dose", propOrder = {
    "dosageInstructionText", "additionalInstructions", "doseType",
    "doseQuantity", "doseRestriction", "doseGoal", "approachBodySite",
    "targetBodySite", "deliveryRoute", "deliveryMethod", "deliveryRate",
    "deliveryRateIncrement", "deliveryRateIncrementInterval",
    "deliveryRateGoal", "infuseOver", "maximumDeliveryRate",
    "maximumDeliveredVolume", "frequency"
})
public class Dose extends ExtendedVmrTypeBase {

  protected ST dosageInstructionText;

  protected List<CD> additionalInstructions;

  protected CD doseType;

  protected IVLPQ doseQuantity;

  protected DoseRestriction doseRestriction;

  protected DoseRestriction doseGoal;

  protected BodySite approachBodySite;

  protected BodySite targetBodySite;

  protected CD deliveryRoute;

  protected CD deliveryMethod;

  protected IVLPQ deliveryRate;

  protected IVLPQ deliveryRateIncrement;

  protected IVLPQ deliveryRateIncrementInterval;

  protected IVLPQ deliveryRateGoal;

  protected PQ infuseOver;

  protected PQ maximumDeliveryRate;

  protected PQ maximumDeliveredVolume;

  protected Schedule frequency;

  /**
   * Gets the value of the dosageInstructionText property.
   * 
   * @return possible object is {@link ST }
   * 
   */
  public ST getDosageInstructionText() {
    return dosageInstructionText;
  }

  /**
   * Sets the value of the dosageInstructionText property.
   * 
   * @param value allowed object is {@link ST }
   * 
   */
  public void setDosageInstructionText(ST value) {
    this.dosageInstructionText = value;
  }

  /**
   * Gets the value of the additionalInstructions property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot.
   * Therefore any modification you make to the returned list will be present
   * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
   * for the additionalInstructions property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
   * getAdditionalInstructions().add(newItem);
   * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list {@link CD }
   * 
   * 
   */
  public List<CD> getAdditionalInstructions() {
    if (additionalInstructions == null) {
      additionalInstructions = new ArrayList<CD>();
    }
    return this.additionalInstructions;
  }

  /**
   * Gets the value of the doseType property.
   * 
   * @return possible object is {@link CD }
   * 
   */
  public CD getDoseType() {
    return doseType;
  }

  /**
   * Sets the value of the doseType property.
   * 
   * @param value allowed object is {@link CD }
   * 
   */
  public void setDoseType(CD value) {
    this.doseType = value;
  }

  /**
   * Gets the value of the doseQuantity property.
   * 
   * @return possible object is {@link IVLPQ }
   * 
   */
  public IVLPQ getDoseQuantity() {
    return doseQuantity;
  }

  /**
   * Sets the value of the doseQuantity property.
   * 
   * @param value allowed object is {@link IVLPQ }
   * 
   */
  public void setDoseQuantity(IVLPQ value) {
    this.doseQuantity = value;
  }

  /**
   * Gets the value of the doseRestriction property.
   * 
   * @return possible object is {@link DoseRestriction }
   * 
   */
  public DoseRestriction getDoseRestriction() {
    return doseRestriction;
  }

  /**
   * Sets the value of the doseRestriction property.
   * 
   * @param value allowed object is {@link DoseRestriction }
   * 
   */
  public void setDoseRestriction(DoseRestriction value) {
    this.doseRestriction = value;
  }

  /**
   * Gets the value of the doseGoal property.
   * 
   * @return possible object is {@link DoseRestriction }
   * 
   */
  public DoseRestriction getDoseGoal() {
    return doseGoal;
  }

  /**
   * Sets the value of the doseGoal property.
   * 
   * @param value allowed object is {@link DoseRestriction }
   * 
   */
  public void setDoseGoal(DoseRestriction value) {
    this.doseGoal = value;
  }

  /**
   * Gets the value of the approachBodySite property.
   * 
   * @return possible object is {@link BodySite }
   * 
   */
  public BodySite getApproachBodySite() {
    return approachBodySite;
  }

  /**
   * Sets the value of the approachBodySite property.
   * 
   * @param value allowed object is {@link BodySite }
   * 
   */
  public void setApproachBodySite(BodySite value) {
    this.approachBodySite = value;
  }

  /**
   * Gets the value of the targetBodySite property.
   * 
   * @return possible object is {@link BodySite }
   * 
   */
  public BodySite getTargetBodySite() {
    return targetBodySite;
  }

  /**
   * Sets the value of the targetBodySite property.
   * 
   * @param value allowed object is {@link BodySite }
   * 
   */
  public void setTargetBodySite(BodySite value) {
    this.targetBodySite = value;
  }

  /**
   * Gets the value of the deliveryRoute property.
   * 
   * @return possible object is {@link CD }
   * 
   */
  public CD getDeliveryRoute() {
    return deliveryRoute;
  }

  /**
   * Sets the value of the deliveryRoute property.
   * 
   * @param value allowed object is {@link CD }
   * 
   */
  public void setDeliveryRoute(CD value) {
    this.deliveryRoute = value;
  }

  /**
   * Gets the value of the deliveryMethod property.
   * 
   * @return possible object is {@link CD }
   * 
   */
  public CD getDeliveryMethod() {
    return deliveryMethod;
  }

  /**
   * Sets the value of the deliveryMethod property.
   * 
   * @param value allowed object is {@link CD }
   * 
   */
  public void setDeliveryMethod(CD value) {
    this.deliveryMethod = value;
  }

  /**
   * Gets the value of the deliveryRate property.
   * 
   * @return possible object is {@link IVLPQ }
   * 
   */
  public IVLPQ getDeliveryRate() {
    return deliveryRate;
  }

  /**
   * Sets the value of the deliveryRate property.
   * 
   * @param value allowed object is {@link IVLPQ }
   * 
   */
  public void setDeliveryRate(IVLPQ value) {
    this.deliveryRate = value;
  }

  /**
   * Gets the value of the deliveryRateIncrement property.
   * 
   * @return possible object is {@link IVLPQ }
   * 
   */
  public IVLPQ getDeliveryRateIncrement() {
    return deliveryRateIncrement;
  }

  /**
   * Sets the value of the deliveryRateIncrement property.
   * 
   * @param value allowed object is {@link IVLPQ }
   * 
   */
  public void setDeliveryRateIncrement(IVLPQ value) {
    this.deliveryRateIncrement = value;
  }

  /**
   * Gets the value of the deliveryRateIncrementInterval property.
   * 
   * @return possible object is {@link IVLPQ }
   * 
   */
  public IVLPQ getDeliveryRateIncrementInterval() {
    return deliveryRateIncrementInterval;
  }

  /**
   * Sets the value of the deliveryRateIncrementInterval property.
   * 
   * @param value allowed object is {@link IVLPQ }
   * 
   */
  public void setDeliveryRateIncrementInterval(IVLPQ value) {
    this.deliveryRateIncrementInterval = value;
  }

  /**
   * Gets the value of the deliveryRateGoal property.
   * 
   * @return possible object is {@link IVLPQ }
   * 
   */
  public IVLPQ getDeliveryRateGoal() {
    return deliveryRateGoal;
  }

  /**
   * Sets the value of the deliveryRateGoal property.
   * 
   * @param value allowed object is {@link IVLPQ }
   * 
   */
  public void setDeliveryRateGoal(IVLPQ value) {
    this.deliveryRateGoal = value;
  }

  /**
   * Gets the value of the infuseOver property.
   * 
   * @return possible object is {@link PQ }
   * 
   */
  public PQ getInfuseOver() {
    return infuseOver;
  }

  /**
   * Sets the value of the infuseOver property.
   * 
   * @param value allowed object is {@link PQ }
   * 
   */
  public void setInfuseOver(PQ value) {
    this.infuseOver = value;
  }

  /**
   * Gets the value of the maximumDeliveryRate property.
   * 
   * @return possible object is {@link PQ }
   * 
   */
  public PQ getMaximumDeliveryRate() {
    return maximumDeliveryRate;
  }

  /**
   * Sets the value of the maximumDeliveryRate property.
   * 
   * @param value allowed object is {@link PQ }
   * 
   */
  public void setMaximumDeliveryRate(PQ value) {
    this.maximumDeliveryRate = value;
  }

  /**
   * Gets the value of the maximumDeliveredVolume property.
   * 
   * @return possible object is {@link PQ }
   * 
   */
  public PQ getMaximumDeliveredVolume() {
    return maximumDeliveredVolume;
  }

  /**
   * Sets the value of the maximumDeliveredVolume property.
   * 
   * @param value allowed object is {@link PQ }
   * 
   */
  public void setMaximumDeliveredVolume(PQ value) {
    this.maximumDeliveredVolume = value;
  }

  /**
   * Gets the value of the frequency property.
   * 
   * @return possible object is {@link Schedule }
   * 
   */
  public Schedule getFrequency() {
    return frequency;
  }

  /**
   * Sets the value of the frequency property.
   * 
   * @param value allowed object is {@link Schedule }
   * 
   */
  public void setFrequency(Schedule value) {
    this.frequency = value;
  }

}
