//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.26 at 04:34:25 PM PDT 
//

package org.hl7.vmr.r2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import org.hl7.cdsdt.r2.CD;
import org.hl7.cdsdt.r2.IVLTS;

/**
 * A clinical end or aim towards which effort is directed.
 * 
 * <p>
 * Java class for Goal complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Goal">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:hl7-org:vmr:r2}GoalBase">
 *       &lt;sequence>
 *         &lt;element name="criticality" type="{urn:hl7-org:cdsdt:r2}CD" minOccurs="0"/>
 *         &lt;element name="goalObserverEventTime" type="{urn:hl7-org:cdsdt:r2}IVL_TS" minOccurs="0"/>
 *         &lt;element name="goalStatus" type="{urn:hl7-org:cdsdt:r2}CD" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Goal", propOrder = {
    "criticality", "goalObserverEventTime", "goalStatus"
})
public class Goal extends GoalBase {

  protected CD criticality;

  protected IVLTS goalObserverEventTime;

  protected CD goalStatus;

  /**
   * Gets the value of the criticality property.
   * 
   * @return possible object is {@link CD }
   * 
   */
  public CD getCriticality() {
    return criticality;
  }

  /**
   * Sets the value of the criticality property.
   * 
   * @param value allowed object is {@link CD }
   * 
   */
  public void setCriticality(CD value) {
    this.criticality = value;
  }

  /**
   * Gets the value of the goalObserverEventTime property.
   * 
   * @return possible object is {@link IVLTS }
   * 
   */
  public IVLTS getGoalObserverEventTime() {
    return goalObserverEventTime;
  }

  /**
   * Sets the value of the goalObserverEventTime property.
   * 
   * @param value allowed object is {@link IVLTS }
   * 
   */
  public void setGoalObserverEventTime(IVLTS value) {
    this.goalObserverEventTime = value;
  }

  /**
   * Gets the value of the goalStatus property.
   * 
   * @return possible object is {@link CD }
   * 
   */
  public CD getGoalStatus() {
    return goalStatus;
  }

  /**
   * Sets the value of the goalStatus property.
   * 
   * @param value allowed object is {@link CD }
   * 
   */
  public void setGoalStatus(CD value) {
    this.goalStatus = value;
  }

}
