//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.30 at 06:15:10 PM PDT 
//


package org.hl7.vmr.r2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import org.hl7.cdsdt.r2.CD;


/**
 * A clinical statement which serves to group other clinical statements.  For example, a grouping clinical statement could contain an intervention proposal and a substance administration proposal, one of which should be completed.
 * 
 * <p>Java class for GroupingClinicalStatement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GroupingClinicalStatement">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:hl7-org:vmr:r2}ClinicalStatement">
 *       &lt;sequence>
 *         &lt;element name="groupingConcept" type="{urn:hl7-org:cdsdt:r2}CD" minOccurs="0"/>
 *         &lt;element name="componentRequirements" type="{urn:hl7-org:cdsdt:r2}CD" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GroupingClinicalStatement", propOrder = {
    "groupingConcept",
    "componentRequirements"
})
public class GroupingClinicalStatement
    extends ClinicalStatement
{

    protected CD groupingConcept;
    protected CD componentRequirements;

    /**
     * Gets the value of the groupingConcept property.
     * 
     * @return
     *     possible object is
     *     {@link CD }
     *     
     */
    public CD getGroupingConcept() {
        return groupingConcept;
    }

    /**
     * Sets the value of the groupingConcept property.
     * 
     * @param value
     *     allowed object is
     *     {@link CD }
     *     
     */
    public void setGroupingConcept(CD value) {
        this.groupingConcept = value;
    }

    /**
     * Gets the value of the componentRequirements property.
     * 
     * @return
     *     possible object is
     *     {@link CD }
     *     
     */
    public CD getComponentRequirements() {
        return componentRequirements;
    }

    /**
     * Sets the value of the componentRequirements property.
     * 
     * @param value
     *     allowed object is
     *     {@link CD }
     *     
     */
    public void setComponentRequirements(CD value) {
        this.componentRequirements = value;
    }

}
