//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.30 at 06:15:10 PM PDT 
//


package org.hl7.vmr.r2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import org.hl7.cdsdt.r2.BL;
import org.hl7.cdsdt.r2.CD;
import org.hl7.cdsdt.r2.IVLPQ;


/**
 * A proposal for an Imaging Order. For instance, Chest Radiograph - PA and Lateral.
 * 
 * <p>Java class for ImagingProposal complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ImagingProposal">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:hl7-org:vmr:r2}ProcedureProposal">
 *       &lt;sequence>
 *         &lt;element name="contrast" type="{urn:hl7-org:cdsdt:r2}BL" minOccurs="0"/>
 *         &lt;element name="contrastRoute" type="{urn:hl7-org:cdsdt:r2}CD" minOccurs="0"/>
 *         &lt;element name="contrastType" type="{urn:hl7-org:cdsdt:r2}CD" minOccurs="0"/>
 *         &lt;element name="isolationCode" type="{urn:hl7-org:cdsdt:r2}CD" minOccurs="0"/>
 *         &lt;element name="portableExam" type="{urn:hl7-org:cdsdt:r2}BL" minOccurs="0"/>
 *         &lt;element name="sedation" type="{urn:hl7-org:cdsdt:r2}BL" minOccurs="0"/>
 *         &lt;element name="stressor" type="{urn:hl7-org:cdsdt:r2}CD" minOccurs="0"/>
 *         &lt;element name="transportMode" type="{urn:hl7-org:cdsdt:r2}CD" minOccurs="0"/>
 *         &lt;element name="radiationDose" type="{urn:hl7-org:cdsdt:r2}IVL_PQ" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ImagingProposal", propOrder = {
    "contrast",
    "contrastRoute",
    "contrastType",
    "isolationCode",
    "portableExam",
    "sedation",
    "stressor",
    "transportMode",
    "radiationDose"
})
public class ImagingProposal
    extends ProcedureProposal
{

    protected BL contrast;
    protected CD contrastRoute;
    protected CD contrastType;
    protected CD isolationCode;
    protected BL portableExam;
    protected BL sedation;
    protected CD stressor;
    protected CD transportMode;
    protected IVLPQ radiationDose;

    /**
     * Gets the value of the contrast property.
     * 
     * @return
     *     possible object is
     *     {@link BL }
     *     
     */
    public BL getContrast() {
        return contrast;
    }

    /**
     * Sets the value of the contrast property.
     * 
     * @param value
     *     allowed object is
     *     {@link BL }
     *     
     */
    public void setContrast(BL value) {
        this.contrast = value;
    }

    /**
     * Gets the value of the contrastRoute property.
     * 
     * @return
     *     possible object is
     *     {@link CD }
     *     
     */
    public CD getContrastRoute() {
        return contrastRoute;
    }

    /**
     * Sets the value of the contrastRoute property.
     * 
     * @param value
     *     allowed object is
     *     {@link CD }
     *     
     */
    public void setContrastRoute(CD value) {
        this.contrastRoute = value;
    }

    /**
     * Gets the value of the contrastType property.
     * 
     * @return
     *     possible object is
     *     {@link CD }
     *     
     */
    public CD getContrastType() {
        return contrastType;
    }

    /**
     * Sets the value of the contrastType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CD }
     *     
     */
    public void setContrastType(CD value) {
        this.contrastType = value;
    }

    /**
     * Gets the value of the isolationCode property.
     * 
     * @return
     *     possible object is
     *     {@link CD }
     *     
     */
    public CD getIsolationCode() {
        return isolationCode;
    }

    /**
     * Sets the value of the isolationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CD }
     *     
     */
    public void setIsolationCode(CD value) {
        this.isolationCode = value;
    }

    /**
     * Gets the value of the portableExam property.
     * 
     * @return
     *     possible object is
     *     {@link BL }
     *     
     */
    public BL getPortableExam() {
        return portableExam;
    }

    /**
     * Sets the value of the portableExam property.
     * 
     * @param value
     *     allowed object is
     *     {@link BL }
     *     
     */
    public void setPortableExam(BL value) {
        this.portableExam = value;
    }

    /**
     * Gets the value of the sedation property.
     * 
     * @return
     *     possible object is
     *     {@link BL }
     *     
     */
    public BL getSedation() {
        return sedation;
    }

    /**
     * Sets the value of the sedation property.
     * 
     * @param value
     *     allowed object is
     *     {@link BL }
     *     
     */
    public void setSedation(BL value) {
        this.sedation = value;
    }

    /**
     * Gets the value of the stressor property.
     * 
     * @return
     *     possible object is
     *     {@link CD }
     *     
     */
    public CD getStressor() {
        return stressor;
    }

    /**
     * Sets the value of the stressor property.
     * 
     * @param value
     *     allowed object is
     *     {@link CD }
     *     
     */
    public void setStressor(CD value) {
        this.stressor = value;
    }

    /**
     * Gets the value of the transportMode property.
     * 
     * @return
     *     possible object is
     *     {@link CD }
     *     
     */
    public CD getTransportMode() {
        return transportMode;
    }

    /**
     * Sets the value of the transportMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CD }
     *     
     */
    public void setTransportMode(CD value) {
        this.transportMode = value;
    }

    /**
     * Gets the value of the radiationDose property.
     * 
     * @return
     *     possible object is
     *     {@link IVLPQ }
     *     
     */
    public IVLPQ getRadiationDose() {
        return radiationDose;
    }

    /**
     * Sets the value of the radiationDose property.
     * 
     * @param value
     *     allowed object is
     *     {@link IVLPQ }
     *     
     */
    public void setRadiationDose(IVLPQ value) {
        this.radiationDose = value;
    }

}
