//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.30 at 06:15:10 PM PDT 
//


package org.hl7.vmr.r2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Use this class to model 'No known allergies' or 'No known drug allergies', or more generally, no known allergy to a class of substances. 
 * 
 * Common denials of allergies or intolerances to a class of agents can be expressed as follows:
 * 
 * 
 * 	- No known allergies --> NoKnownAllergy with a conditionCode stating 'No known allergies'. 
 * 	- No known drug allergies --> NoKnownAllergy  with conditionCode stating 'No known drug allergies'.  
 * 	- No known food allergies --> NoKnownAllergy  with conditionCode stating 'No known food allergies'. 
 * 
 * <p>Java class for NoKnownAllergy complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NoKnownAllergy">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:hl7-org:vmr:r2}AbstractDeniedCondition">
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NoKnownAllergy")
public class NoKnownAllergy
    extends AbstractDeniedCondition
{


}
