//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.26 at 04:34:25 PM PDT 
//

package org.hl7.vmr.r2;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the org.hl7.vmr.r2 package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

  private final static QName _VMR_QNAME =
      new QName("urn:hl7-org:vmr:r2", "vMR");

  /**
   * Create a new ObjectFactory that can be used to create new instances of
   * schema derived classes for package: org.hl7.vmr.r2
   * 
   */
  public ObjectFactory() {
  }

  /**
   * Create an instance of {@link VMR }
   * 
   */
  public VMR createVMR() {
    return new VMR();
  }

  /**
   * Create an instance of {@link SubstanceAdministrationOrder }
   * 
   */
  public SubstanceAdministrationOrder createSubstanceAdministrationOrder() {
    return new SubstanceAdministrationOrder();
  }

  /**
   * Create an instance of {@link Qualification }
   * 
   */
  public Qualification createQualification() {
    return new Qualification();
  }

  /**
   * Create an instance of {@link SubstanceDispenseEvent }
   * 
   */
  public SubstanceDispenseEvent createSubstanceDispenseEvent() {
    return new SubstanceDispenseEvent();
  }

  /**
   * Create an instance of {@link EnteralFeedingDispenseProposal }
   * 
   */
  public EnteralFeedingDispenseProposal createEnteralFeedingDispenseProposal() {
    return new EnteralFeedingDispenseProposal();
  }

  /**
   * Create an instance of {@link ObservationResult }
   * 
   */
  public ObservationResult createObservationResult() {
    return new ObservationResult();
  }

  /**
   * Create an instance of {@link RadiotherapyOrder }
   * 
   */
  public RadiotherapyOrder createRadiotherapyOrder() {
    return new RadiotherapyOrder();
  }

  /**
   * Create an instance of {@link RelatedClinicalStatement }
   * 
   */
  public RelatedClinicalStatement createRelatedClinicalStatement() {
    return new RelatedClinicalStatement();
  }

  /**
   * Create an instance of {@link ImagingOrder }
   * 
   */
  public ImagingOrder createImagingOrder() {
    return new ImagingOrder();
  }

  /**
   * Create an instance of {@link SubstanceDispenseOrder }
   * 
   */
  public SubstanceDispenseOrder createSubstanceDispenseOrder() {
    return new SubstanceDispenseOrder();
  }

  /**
   * Create an instance of {@link ClinicalStatement }
   * 
   */
  public ClinicalStatement createClinicalStatement() {
    return new ClinicalStatement();
  }

  /**
   * Create an instance of {@link ScheduledAppointment }
   * 
   */
  public ScheduledAppointment createScheduledAppointment() {
    return new ScheduledAppointment();
  }

  /**
   * Create an instance of {@link LaboratoryProposal }
   * 
   */
  public LaboratoryProposal createLaboratoryProposal() {
    return new LaboratoryProposal();
  }

  /**
   * Create an instance of {@link SubstanceDispenseProposal }
   * 
   */
  public SubstanceDispenseProposal createSubstanceDispenseProposal() {
    return new SubstanceDispenseProposal();
  }

  /**
   * Create an instance of {@link ProcedureEvent }
   * 
   */
  public ProcedureEvent createProcedureEvent() {
    return new ProcedureEvent();
  }

  /**
   * Create an instance of {@link DoseRestriction }
   * 
   */
  public DoseRestriction createDoseRestriction() {
    return new DoseRestriction();
  }

  /**
   * Create an instance of {@link AdverseEvent }
   * 
   */
  public AdverseEvent createAdverseEvent() {
    return new AdverseEvent();
  }

  /**
   * Create an instance of {@link CompositeSubstanceOrder }
   * 
   */
  public CompositeSubstanceOrder createCompositeSubstanceOrder() {
    return new CompositeSubstanceOrder();
  }

  /**
   * Create an instance of {@link TextureModification }
   * 
   */
  public TextureModification createTextureModification() {
    return new TextureModification();
  }

  /**
   * Create an instance of {@link GoalProposal }
   * 
   */
  public GoalProposal createGoalProposal() {
    return new GoalProposal();
  }

  /**
   * Create an instance of {@link RadiotherapyProposal }
   * 
   */
  public RadiotherapyProposal createRadiotherapyProposal() {
    return new RadiotherapyProposal();
  }

  /**
   * Create an instance of {@link CodedRecurringEvent }
   * 
   */
  public CodedRecurringEvent createCodedRecurringEvent() {
    return new CodedRecurringEvent();
  }

  /**
   * Create an instance of {@link ProcedureProposal }
   * 
   */
  public ProcedureProposal createProcedureProposal() {
    return new ProcedureProposal();
  }

  /**
   * Create an instance of {@link Cycle }
   * 
   */
  public Cycle createCycle() {
    return new Cycle();
  }

  /**
   * Create an instance of {@link PCAProposal }
   * 
   */
  public PCAProposal createPCAProposal() {
    return new PCAProposal();
  }

  /**
   * Create an instance of {@link Practitioner }
   * 
   */
  public Practitioner createPractitioner() {
    return new Practitioner();
  }

  /**
   * Create an instance of {@link StringNameValuePair }
   * 
   */
  public StringNameValuePair createStringNameValuePair() {
    return new StringNameValuePair();
  }

  /**
   * Create an instance of {@link UndeliveredProcedure }
   * 
   */
  public UndeliveredProcedure createUndeliveredProcedure() {
    return new UndeliveredProcedure();
  }

  /**
   * Create an instance of {@link EvaluatedPerson }
   * 
   */
  public EvaluatedPerson createEvaluatedPerson() {
    return new EvaluatedPerson();
  }

  /**
   * Create an instance of {@link Schedule }
   * 
   */
  public Schedule createSchedule() {
    return new Schedule();
  }

  /**
   * Create an instance of {@link AdministrableSubstance }
   * 
   */
  public AdministrableSubstance createAdministrableSubstance() {
    return new AdministrableSubstance();
  }

  /**
   * Create an instance of {@link MissedAppointment }
   * 
   */
  public MissedAppointment createMissedAppointment() {
    return new MissedAppointment();
  }

  /**
   * Create an instance of {@link SupplyEvent }
   * 
   */
  public SupplyEvent createSupplyEvent() {
    return new SupplyEvent();
  }

  /**
   * Create an instance of {@link DeniedAllergyOrIntolerance }
   * 
   */
  public DeniedAllergyOrIntolerance createDeniedAllergyOrIntolerance() {
    return new DeniedAllergyOrIntolerance();
  }

  /**
   * Create an instance of {@link ProcedureOrder }
   * 
   */
  public ProcedureOrder createProcedureOrder() {
    return new ProcedureOrder();
  }

  /**
   * Create an instance of {@link EnteralFeedingDispenseOrder }
   * 
   */
  public EnteralFeedingDispenseOrder createEnteralFeedingDispenseOrder() {
    return new EnteralFeedingDispenseOrder();
  }

  /**
   * Create an instance of {@link BodySite }
   * 
   */
  public BodySite createBodySite() {
    return new BodySite();
  }

  /**
   * Create an instance of {@link RelatedEvaluatedPerson }
   * 
   */
  public RelatedEvaluatedPerson createRelatedEvaluatedPerson() {
    return new RelatedEvaluatedPerson();
  }

  /**
   * Create an instance of {@link AllergyOrIntolerance }
   * 
   */
  public AllergyOrIntolerance createAllergyOrIntolerance() {
    return new AllergyOrIntolerance();
  }

  /**
   * Create an instance of {@link DeniedAdverseEvent }
   * 
   */
  public DeniedAdverseEvent createDeniedAdverseEvent() {
    return new DeniedAdverseEvent();
  }

  /**
   * Create an instance of {@link NoKnownAllergy }
   * 
   */
  public NoKnownAllergy createNoKnownAllergy() {
    return new NoKnownAllergy();
  }

  /**
   * Create an instance of {@link RespiratoryCareOrder }
   * 
   */
  public RespiratoryCareOrder createRespiratoryCareOrder() {
    return new RespiratoryCareOrder();
  }

  /**
   * Create an instance of {@link AppointmentRequest }
   * 
   */
  public AppointmentRequest createAppointmentRequest() {
    return new AppointmentRequest();
  }

  /**
   * Create an instance of {@link SupplyProposal }
   * 
   */
  public SupplyProposal createSupplyProposal() {
    return new SupplyProposal();
  }

  /**
   * Create an instance of {@link DeniedProblem }
   * 
   */
  public DeniedProblem createDeniedProblem() {
    return new DeniedProblem();
  }

  /**
   * Create an instance of {@link Constituent }
   * 
   */
  public Constituent createConstituent() {
    return new Constituent();
  }

  /**
   * Create an instance of {@link Facility }
   * 
   */
  public Facility createFacility() {
    return new Facility();
  }

  /**
   * Create an instance of {@link OralDietOrder }
   * 
   */
  public OralDietOrder createOralDietOrder() {
    return new OralDietOrder();
  }

  /**
   * Create an instance of {@link EnteralFeedingOrder }
   * 
   */
  public EnteralFeedingOrder createEnteralFeedingOrder() {
    return new EnteralFeedingOrder();
  }

  /**
   * Create an instance of {@link Person }
   * 
   */
  public Person createPerson() {
    return new Person();
  }

  /**
   * Create an instance of {@link ScheduledProcedure }
   * 
   */
  public ScheduledProcedure createScheduledProcedure() {
    return new ScheduledProcedure();
  }

  /**
   * Create an instance of {@link UndeliveredSupply }
   * 
   */
  public UndeliveredSupply createUndeliveredSupply() {
    return new UndeliveredSupply();
  }

  /**
   * Create an instance of {@link Organization }
   * 
   */
  public Organization createOrganization() {
    return new Organization();
  }

  /**
   * Create an instance of {@link OralDietProposal }
   * 
   */
  public OralDietProposal createOralDietProposal() {
    return new OralDietProposal();
  }

  /**
   * Create an instance of {@link CommunicationOrder }
   * 
   */
  public CommunicationOrder createCommunicationOrder() {
    return new CommunicationOrder();
  }

  /**
   * Create an instance of {@link SupplyOrder }
   * 
   */
  public SupplyOrder createSupplyOrder() {
    return new SupplyOrder();
  }

  /**
   * Create an instance of {@link CommunicationProposal }
   * 
   */
  public CommunicationProposal createCommunicationProposal() {
    return new CommunicationProposal();
  }

  /**
   * Create an instance of {@link SubstanceAdministrationEvent }
   * 
   */
  public SubstanceAdministrationEvent createSubstanceAdministrationEvent() {
    return new SubstanceAdministrationEvent();
  }

  /**
   * Create an instance of {@link Dose }
   * 
   */
  public Dose createDose() {
    return new Dose();
  }

  /**
   * Create an instance of {@link Value }
   * 
   */
  public Value createValue() {
    return new Value();
  }

  /**
   * Create an instance of {@link AnchoredEvent }
   * 
   */
  public AnchoredEvent createAnchoredEvent() {
    return new AnchoredEvent();
  }

  /**
   * Create an instance of {@link CommunicationEvent }
   * 
   */
  public CommunicationEvent createCommunicationEvent() {
    return new CommunicationEvent();
  }

  /**
   * Create an instance of {@link CompositeObservationResult }
   * 
   */
  public CompositeObservationResult createCompositeObservationResult() {
    return new CompositeObservationResult();
  }

  /**
   * Create an instance of {@link RecurringEvent }
   * 
   */
  public RecurringEvent createRecurringEvent() {
    return new RecurringEvent();
  }

  /**
   * Create an instance of {@link RelatedEntity }
   * 
   */
  public RelatedEntity createRelatedEntity() {
    return new RelatedEntity();
  }

  /**
   * Create an instance of {@link Problem }
   * 
   */
  public Problem createProblem() {
    return new Problem();
  }

  /**
   * Create an instance of {@link ImagingProposal }
   * 
   */
  public ImagingProposal createImagingProposal() {
    return new ImagingProposal();
  }

  /**
   * Create an instance of {@link NutrientModification }
   * 
   */
  public NutrientModification createNutrientModification() {
    return new NutrientModification();
  }

  /**
   * Create an instance of {@link RespiratoryCareProposal }
   * 
   */
  public RespiratoryCareProposal createRespiratoryCareProposal() {
    return new RespiratoryCareProposal();
  }

  /**
   * Create an instance of {@link EnteralFeedingProposal }
   * 
   */
  public EnteralFeedingProposal createEnteralFeedingProposal() {
    return new EnteralFeedingProposal();
  }

  /**
   * Create an instance of {@link PCAOrder }
   * 
   */
  public PCAOrder createPCAOrder() {
    return new PCAOrder();
  }

  /**
   * Create an instance of {@link SubstanceAdministrationProposal }
   * 
   */
  public SubstanceAdministrationProposal createSubstanceAdministrationProposal() {
    return new SubstanceAdministrationProposal();
  }

  /**
   * Create an instance of {@link Entity }
   * 
   */
  public Entity createEntity() {
    return new Entity();
  }

  /**
   * Create an instance of {@link Documentation }
   * 
   */
  public Documentation createDocumentation() {
    return new Documentation();
  }

  /**
   * Create an instance of {@link Device }
   * 
   */
  public Device createDevice() {
    return new Device();
  }

  /**
   * Create an instance of {@link MotionManagement }
   * 
   */
  public MotionManagement createMotionManagement() {
    return new MotionManagement();
  }

  /**
   * Create an instance of {@link EncounterEvent }
   * 
   */
  public EncounterEvent createEncounterEvent() {
    return new EncounterEvent();
  }

  /**
   * Create an instance of {@link RadiotherapySimulation }
   * 
   */
  public RadiotherapySimulation createRadiotherapySimulation() {
    return new RadiotherapySimulation();
  }

  /**
   * Create an instance of {@link LocalizationMethod }
   * 
   */
  public LocalizationMethod createLocalizationMethod() {
    return new LocalizationMethod();
  }

  /**
   * Create an instance of {@link VaccinationProtocol }
   * 
   */
  public VaccinationProtocol createVaccinationProtocol() {
    return new VaccinationProtocol();
  }

  /**
   * Create an instance of {@link Goal }
   * 
   */
  public Goal createGoal() {
    return new Goal();
  }

  /**
   * Create an instance of {@link LaboratoryOrder }
   * 
   */
  public LaboratoryOrder createLaboratoryOrder() {
    return new LaboratoryOrder();
  }

  /**
   * Create an instance of {@link NameValuePair }
   * 
   */
  public NameValuePair createNameValuePair() {
    return new NameValuePair();
  }

  /**
   * Create an instance of {@link GroupingClinicalStatement }
   * 
   */
  public GroupingClinicalStatement createGroupingClinicalStatement() {
    return new GroupingClinicalStatement();
  }

  /**
   * Create an instance of {@link CompositeSubstanceProposal }
   * 
   */
  public CompositeSubstanceProposal createCompositeSubstanceProposal() {
    return new CompositeSubstanceProposal();
  }

  /**
   * Create an instance of {@link UndeliveredSubstanceAdministration }
   * 
   */
  public UndeliveredSubstanceAdministration createUndeliveredSubstanceAdministration() {
    return new UndeliveredSubstanceAdministration();
  }

  /**
   * Create an instance of {@link Specimen }
   * 
   */
  public Specimen createSpecimen() {
    return new Specimen();
  }

  /**
   * Create an instance of {@link CodedIdentifier }
   * 
   */
  public CodedIdentifier createCodedIdentifier() {
    return new CodedIdentifier();
  }

  /**
   * Create an instance of {@link AppointmentProposal }
   * 
   */
  public AppointmentProposal createAppointmentProposal() {
    return new AppointmentProposal();
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link VMR }{@code >}
   * 
   */
  @XmlElementDecl(namespace = "urn:hl7-org:vmr:r2", name = "vMR")
  public JAXBElement<VMR> createVMR(VMR value) {
    return new JAXBElement<VMR>(_VMR_QNAME, VMR.class, null, value);
  }

}
