//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.26 at 04:34:25 PM PDT 
//

package org.hl7.vmr.r2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import org.hl7.cdsdt.r2.AD;
import org.hl7.cdsdt.r2.CD;
import org.hl7.cdsdt.r2.EN;
import org.hl7.cdsdt.r2.PQ;
import org.hl7.cdsdt.r2.TEL;
import org.hl7.cdsdt.r2.TS;

/**
 * A human being.
 * 
 * <p>
 * Java class for Person complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Person">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:hl7-org:vmr:r2}Entity">
 *       &lt;sequence>
 *         &lt;element name="name" type="{urn:hl7-org:cdsdt:r2}EN" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="address" type="{urn:hl7-org:cdsdt:r2}AD" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="telecom" type="{urn:hl7-org:cdsdt:r2}TEL" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="race" type="{urn:hl7-org:cdsdt:r2}CD" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ethnicity" type="{urn:hl7-org:cdsdt:r2}CD" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="gender" type="{urn:hl7-org:cdsdt:r2}CD" minOccurs="0"/>
 *         &lt;element name="birthTime" type="{urn:hl7-org:cdsdt:r2}TS" minOccurs="0"/>
 *         &lt;element name="age" type="{urn:hl7-org:cdsdt:r2}PQ" minOccurs="0"/>
 *         &lt;element name="preferredLanguage" type="{urn:hl7-org:cdsdt:r2}CD" minOccurs="0"/>
 *         &lt;element name="communication" type="{urn:hl7-org:cdsdt:r2}CD" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Person", propOrder = {
    "name", "address", "telecom", "race", "ethnicity", "gender", "birthTime",
    "age", "preferredLanguage", "communication"
})
@XmlSeeAlso({
    Practitioner.class, EvaluatedPerson.class
})
public class Person extends Entity {

  protected List<EN> name;

  protected List<AD> address;

  protected List<TEL> telecom;

  protected List<CD> race;

  protected List<CD> ethnicity;

  protected CD gender;

  protected TS birthTime;

  protected PQ age;

  protected CD preferredLanguage;

  protected List<CD> communication;

  /**
   * Gets the value of the name property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot.
   * Therefore any modification you make to the returned list will be present
   * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
   * for the name property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
   * getName().add(newItem);
   * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list {@link EN }
   * 
   * 
   */
  public List<EN> getName() {
    if (name == null) {
      name = new ArrayList<EN>();
    }
    return this.name;
  }

  /**
   * Gets the value of the address property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot.
   * Therefore any modification you make to the returned list will be present
   * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
   * for the address property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
   * getAddress().add(newItem);
   * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list {@link AD }
   * 
   * 
   */
  public List<AD> getAddress() {
    if (address == null) {
      address = new ArrayList<AD>();
    }
    return this.address;
  }

  /**
   * Gets the value of the telecom property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot.
   * Therefore any modification you make to the returned list will be present
   * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
   * for the telecom property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
   * getTelecom().add(newItem);
   * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list {@link TEL }
   * 
   * 
   */
  public List<TEL> getTelecom() {
    if (telecom == null) {
      telecom = new ArrayList<TEL>();
    }
    return this.telecom;
  }

  /**
   * Gets the value of the race property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot.
   * Therefore any modification you make to the returned list will be present
   * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
   * for the race property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
   * getRace().add(newItem);
   * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list {@link CD }
   * 
   * 
   */
  public List<CD> getRace() {
    if (race == null) {
      race = new ArrayList<CD>();
    }
    return this.race;
  }

  /**
   * Gets the value of the ethnicity property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot.
   * Therefore any modification you make to the returned list will be present
   * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
   * for the ethnicity property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
   * getEthnicity().add(newItem);
   * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list {@link CD }
   * 
   * 
   */
  public List<CD> getEthnicity() {
    if (ethnicity == null) {
      ethnicity = new ArrayList<CD>();
    }
    return this.ethnicity;
  }

  /**
   * Gets the value of the gender property.
   * 
   * @return possible object is {@link CD }
   * 
   */
  public CD getGender() {
    return gender;
  }

  /**
   * Sets the value of the gender property.
   * 
   * @param value allowed object is {@link CD }
   * 
   */
  public void setGender(CD value) {
    this.gender = value;
  }

  /**
   * Gets the value of the birthTime property.
   * 
   * @return possible object is {@link TS }
   * 
   */
  public TS getBirthTime() {
    return birthTime;
  }

  /**
   * Sets the value of the birthTime property.
   * 
   * @param value allowed object is {@link TS }
   * 
   */
  public void setBirthTime(TS value) {
    this.birthTime = value;
  }

  /**
   * Gets the value of the age property.
   * 
   * @return possible object is {@link PQ }
   * 
   */
  public PQ getAge() {
    return age;
  }

  /**
   * Sets the value of the age property.
   * 
   * @param value allowed object is {@link PQ }
   * 
   */
  public void setAge(PQ value) {
    this.age = value;
  }

  /**
   * Gets the value of the preferredLanguage property.
   * 
   * @return possible object is {@link CD }
   * 
   */
  public CD getPreferredLanguage() {
    return preferredLanguage;
  }

  /**
   * Sets the value of the preferredLanguage property.
   * 
   * @param value allowed object is {@link CD }
   * 
   */
  public void setPreferredLanguage(CD value) {
    this.preferredLanguage = value;
  }

  /**
   * Gets the value of the communication property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot.
   * Therefore any modification you make to the returned list will be present
   * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
   * for the communication property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
   * getCommunication().add(newItem);
   * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list {@link CD }
   * 
   * 
   */
  public List<CD> getCommunication() {
    if (communication == null) {
      communication = new ArrayList<CD>();
    }
    return this.communication;
  }

}
