//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.30 at 06:15:10 PM PDT 
//


package org.hl7.vmr.r2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.hl7.cdsdt.r2.BL;
import org.hl7.cdsdt.r2.IVLINT;


/**
 * Specifies timing as a number of times the event occurs in the cycleLength and whether the time interval is important. 
 * 
 * For instance, if the cycle length is 24 hours, the frequencyPerCycle is 3 and the intervalIsImportant is true, this is equivalent to stating that the event should occur every 8 hours (Q8H).
 * 
 * <p>Java class for RecurringEvent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RecurringEvent">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:hl7-org:vmr:r2}CycleEventTiming">
 *       &lt;sequence>
 *         &lt;element name="frequencyPerCycle" type="{urn:hl7-org:cdsdt:r2}IVL_INT"/>
 *         &lt;element name="intervalIsImportant" type="{urn:hl7-org:cdsdt:r2}BL"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RecurringEvent", propOrder = {
    "frequencyPerCycle",
    "intervalIsImportant"
})
public class RecurringEvent
    extends CycleEventTiming
{

    @XmlElement(required = true)
    protected IVLINT frequencyPerCycle;
    @XmlElement(required = true)
    protected BL intervalIsImportant;

    /**
     * Gets the value of the frequencyPerCycle property.
     * 
     * @return
     *     possible object is
     *     {@link IVLINT }
     *     
     */
    public IVLINT getFrequencyPerCycle() {
        return frequencyPerCycle;
    }

    /**
     * Sets the value of the frequencyPerCycle property.
     * 
     * @param value
     *     allowed object is
     *     {@link IVLINT }
     *     
     */
    public void setFrequencyPerCycle(IVLINT value) {
        this.frequencyPerCycle = value;
    }

    /**
     * Gets the value of the intervalIsImportant property.
     * 
     * @return
     *     possible object is
     *     {@link BL }
     *     
     */
    public BL getIntervalIsImportant() {
        return intervalIsImportant;
    }

    /**
     * Sets the value of the intervalIsImportant property.
     * 
     * @param value
     *     allowed object is
     *     {@link BL }
     *     
     */
    public void setIntervalIsImportant(BL value) {
        this.intervalIsImportant = value;
    }

}
