//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.26 at 04:34:25 PM PDT 
//

package org.hl7.vmr.r2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import org.hl7.cdsdt.r2.CD;
import org.hl7.cdsdt.r2.INT;
import org.hl7.cdsdt.r2.IVLTS;

/**
 * A clinical order for the administration of a substance. Describes the event
 * of a patient being given a dose of a medication. This may be as simple as
 * swallowing a tablet or it may be a long running infusion.
 * 
 * Medication prescription represents both the dispense of a medication and
 * dosing instructions. It can be modeled using both a
 * SubstanceAdministrationOrder and a SubstanceDispenseOrder related by a
 * RelatedClinicalStatement or grouped under a GroupedClinicalStatement.
 * 
 * <p>
 * Java class for SubstanceAdministrationOrder complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="SubstanceAdministrationOrder">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:hl7-org:vmr:r2}SubstanceClinicalStatementBase">
 *       &lt;sequence>
 *         &lt;element name="administrationTimeInterval" type="{urn:hl7-org:cdsdt:r2}IVL_TS" minOccurs="0"/>
 *         &lt;element name="numberFillsAllowed" type="{urn:hl7-org:cdsdt:r2}INT" minOccurs="0"/>
 *         &lt;element name="prnReason" type="{urn:hl7-org:cdsdt:r2}CD" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="urgency" type="{urn:hl7-org:cdsdt:r2}CD" minOccurs="0"/>
 *         &lt;element name="validAdministrationTimeInterval" type="{urn:hl7-org:cdsdt:r2}IVL_TS" minOccurs="0"/>
 *         &lt;element name="orderEventTime" type="{urn:hl7-org:cdsdt:r2}IVL_TS" minOccurs="0"/>
 *         &lt;element name="originationMode" type="{urn:hl7-org:cdsdt:r2}CD" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubstanceAdministrationOrder", propOrder = {
    "administrationTimeInterval", "numberFillsAllowed", "prnReason", "urgency",
    "validAdministrationTimeInterval", "orderEventTime", "originationMode"
})
@XmlSeeAlso({
    CompositeSubstanceOrder.class, EnteralFeedingOrder.class, PCAOrder.class
})
public class SubstanceAdministrationOrder extends
    SubstanceClinicalStatementBase {

  protected IVLTS administrationTimeInterval;

  protected INT numberFillsAllowed;

  protected List<CD> prnReason;

  protected CD urgency;

  protected IVLTS validAdministrationTimeInterval;

  protected IVLTS orderEventTime;

  protected CD originationMode;

  /**
   * Gets the value of the administrationTimeInterval property.
   * 
   * @return possible object is {@link IVLTS }
   * 
   */
  public IVLTS getAdministrationTimeInterval() {
    return administrationTimeInterval;
  }

  /**
   * Sets the value of the administrationTimeInterval property.
   * 
   * @param value allowed object is {@link IVLTS }
   * 
   */
  public void setAdministrationTimeInterval(IVLTS value) {
    this.administrationTimeInterval = value;
  }

  /**
   * Gets the value of the numberFillsAllowed property.
   * 
   * @return possible object is {@link INT }
   * 
   */
  public INT getNumberFillsAllowed() {
    return numberFillsAllowed;
  }

  /**
   * Sets the value of the numberFillsAllowed property.
   * 
   * @param value allowed object is {@link INT }
   * 
   */
  public void setNumberFillsAllowed(INT value) {
    this.numberFillsAllowed = value;
  }

  /**
   * Gets the value of the prnReason property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot.
   * Therefore any modification you make to the returned list will be present
   * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
   * for the prnReason property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
   * getPrnReason().add(newItem);
   * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list {@link CD }
   * 
   * 
   */
  public List<CD> getPrnReason() {
    if (prnReason == null) {
      prnReason = new ArrayList<CD>();
    }
    return this.prnReason;
  }

  /**
   * Gets the value of the urgency property.
   * 
   * @return possible object is {@link CD }
   * 
   */
  public CD getUrgency() {
    return urgency;
  }

  /**
   * Sets the value of the urgency property.
   * 
   * @param value allowed object is {@link CD }
   * 
   */
  public void setUrgency(CD value) {
    this.urgency = value;
  }

  /**
   * Gets the value of the validAdministrationTimeInterval property.
   * 
   * @return possible object is {@link IVLTS }
   * 
   */
  public IVLTS getValidAdministrationTimeInterval() {
    return validAdministrationTimeInterval;
  }

  /**
   * Sets the value of the validAdministrationTimeInterval property.
   * 
   * @param value allowed object is {@link IVLTS }
   * 
   */
  public void setValidAdministrationTimeInterval(IVLTS value) {
    this.validAdministrationTimeInterval = value;
  }

  /**
   * Gets the value of the orderEventTime property.
   * 
   * @return possible object is {@link IVLTS }
   * 
   */
  public IVLTS getOrderEventTime() {
    return orderEventTime;
  }

  /**
   * Sets the value of the orderEventTime property.
   * 
   * @param value allowed object is {@link IVLTS }
   * 
   */
  public void setOrderEventTime(IVLTS value) {
    this.orderEventTime = value;
  }

  /**
   * Gets the value of the originationMode property.
   * 
   * @return possible object is {@link CD }
   * 
   */
  public CD getOriginationMode() {
    return originationMode;
  }

  /**
   * Sets the value of the originationMode property.
   * 
   * @param value allowed object is {@link CD }
   * 
   */
  public void setOriginationMode(CD value) {
    this.originationMode = value;
  }

}
