//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.26 at 04:34:25 PM PDT 
//

package org.hl7.vmr.r2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import org.hl7.cdsdt.r2.IVLTS;

/**
 * The provision of some clinical material or equipment to the subject, such as
 * a wheelchair.
 * 
 * <p>
 * Java class for SupplyEvent complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="SupplyEvent">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:hl7-org:vmr:r2}SupplyBase">
 *       &lt;sequence>
 *         &lt;element name="supplyTime" type="{urn:hl7-org:cdsdt:r2}IVL_TS" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SupplyEvent", propOrder = {
  "supplyTime"
})
public class SupplyEvent extends SupplyBase {

  protected IVLTS supplyTime;

  /**
   * Gets the value of the supplyTime property.
   * 
   * @return possible object is {@link IVLTS }
   * 
   */
  public IVLTS getSupplyTime() {
    return supplyTime;
  }

  /**
   * Sets the value of the supplyTime property.
   * 
   * @param value allowed object is {@link IVLTS }
   * 
   */
  public void setSupplyTime(IVLTS value) {
    this.supplyTime = value;
  }

}
