//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.26 at 04:34:25 PM PDT 
//

package org.hl7.vmr.r2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import org.hl7.cdsdt.r2.CD;
import org.hl7.cdsdt.r2.IVLTS;

/**
 * Documentation that the indicated material was not provided to the subject.
 * 
 * <p>
 * Java class for UndeliveredSupply complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="UndeliveredSupply">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:hl7-org:vmr:r2}SupplyBase">
 *       &lt;sequence>
 *         &lt;element name="reason" type="{urn:hl7-org:cdsdt:r2}CD" minOccurs="0"/>
 *         &lt;element name="subjectEffectiveTime" type="{urn:hl7-org:cdsdt:r2}IVL_TS" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UndeliveredSupply", propOrder = {
    "reason", "subjectEffectiveTime"
})
public class UndeliveredSupply extends SupplyBase {

  protected CD reason;

  protected IVLTS subjectEffectiveTime;

  /**
   * Gets the value of the reason property.
   * 
   * @return possible object is {@link CD }
   * 
   */
  public CD getReason() {
    return reason;
  }

  /**
   * Sets the value of the reason property.
   * 
   * @param value allowed object is {@link CD }
   * 
   */
  public void setReason(CD value) {
    this.reason = value;
  }

  /**
   * Gets the value of the subjectEffectiveTime property.
   * 
   * @return possible object is {@link IVLTS }
   * 
   */
  public IVLTS getSubjectEffectiveTime() {
    return subjectEffectiveTime;
  }

  /**
   * Sets the value of the subjectEffectiveTime property.
   * 
   * @param value allowed object is {@link IVLTS }
   * 
   */
  public void setSubjectEffectiveTime(IVLTS value) {
    this.subjectEffectiveTime = value;
  }

}
