//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.30 at 06:15:10 PM PDT 
//


package org.hl7.cdsoutputspecification.r2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import org.hl7.vmr.r2.CodedIdentifier;


/**
 * Specifies the evaluation results to be provided for an evaluated person. Specifies the templates that SHALL or MAY be applied.
 * 
 * <p>Java class for EvaluatedPersonOutputSpecification complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EvaluatedPersonOutputSpecification">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="evaluatedPersonTemplate" type="{urn:hl7-org:vmr:r2}CodedIdentifier" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="potentialEvaluatedPersonTemplate" type="{urn:hl7-org:vmr:r2}CodedIdentifier" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="clinicalStatementOutputSpecification" type="{urn:hl7-org:cdsoutputspecification:r2}ClinicalStatementOutputSpecification" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EvaluatedPersonOutputSpecification", propOrder = {
    "evaluatedPersonTemplate",
    "potentialEvaluatedPersonTemplate",
    "clinicalStatementOutputSpecification"
})
@XmlSeeAlso({
    PatientOutputSpecification.class,
    RelatedEvaluatedPersonOutputSpecification.class
})
public abstract class EvaluatedPersonOutputSpecification {

    protected List<CodedIdentifier> evaluatedPersonTemplate;
    protected List<CodedIdentifier> potentialEvaluatedPersonTemplate;
    protected List<ClinicalStatementOutputSpecification> clinicalStatementOutputSpecification;

    /**
     * Gets the value of the evaluatedPersonTemplate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the evaluatedPersonTemplate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEvaluatedPersonTemplate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodedIdentifier }
     * 
     * 
     */
    public List<CodedIdentifier> getEvaluatedPersonTemplate() {
        if (evaluatedPersonTemplate == null) {
            evaluatedPersonTemplate = new ArrayList<CodedIdentifier>();
        }
        return this.evaluatedPersonTemplate;
    }

    /**
     * Gets the value of the potentialEvaluatedPersonTemplate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the potentialEvaluatedPersonTemplate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPotentialEvaluatedPersonTemplate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodedIdentifier }
     * 
     * 
     */
    public List<CodedIdentifier> getPotentialEvaluatedPersonTemplate() {
        if (potentialEvaluatedPersonTemplate == null) {
            potentialEvaluatedPersonTemplate = new ArrayList<CodedIdentifier>();
        }
        return this.potentialEvaluatedPersonTemplate;
    }

    /**
     * Gets the value of the clinicalStatementOutputSpecification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the clinicalStatementOutputSpecification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClinicalStatementOutputSpecification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ClinicalStatementOutputSpecification }
     * 
     * 
     */
    public List<ClinicalStatementOutputSpecification> getClinicalStatementOutputSpecification() {
        if (clinicalStatementOutputSpecification == null) {
            clinicalStatementOutputSpecification = new ArrayList<ClinicalStatementOutputSpecification>();
        }
        return this.clinicalStatementOutputSpecification;
    }

}
