//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.26 at 04:33:57 PM PDT 
//

package org.hl7.cdsoutput.r2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import org.hl7.vmr.r2.CodedIdentifier;

/**
 * The parent class containing the data used by a CDS system to communicate
 * inferences. Can use the vMR data structure or a base data type to communicate
 * the results.
 * 
 * As a specific example, a CDSOutput may be used as the primary output data
 * payload for a CDS guidance service compliant with the HL7 Decision Support
 * Service standard. Further information regarding this type of use case can be
 * found in the HL7 Decision Support Service specification and the HL7 Decision
 * Support Service Implementation Guide.
 * 
 * <p>
 * Java class for CDSOutput complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="CDSOutput">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="templateId" type="{urn:hl7-org:vmr:r2}CodedIdentifier" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CDSOutput", propOrder = {
  "templateId"
})
@XmlSeeAlso({
    CDSOutputAsVMR.class, CDSOutputAsStringNameValuePairs.class,
    CDSOutputAsDataType.class
})
public abstract class CDSOutput {

  protected List<CodedIdentifier> templateId;

  /**
   * Gets the value of the templateId property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot.
   * Therefore any modification you make to the returned list will be present
   * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
   * for the templateId property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
   * getTemplateId().add(newItem);
   * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link CodedIdentifier }
   * 
   * 
   */
  public List<CodedIdentifier> getTemplateId() {
    if (templateId == null) {
      templateId = new ArrayList<CodedIdentifier>();
    }
    return this.templateId;
  }

}
