//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.30 at 06:15:10 PM PDT 
//


package org.hl7.cdsoutput.r2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.hl7.vmr.r2.StringNameValuePair;


/**
 * A set of string name value pairs to communicate the results.
 * 
 * <p>Java class for CDSOutputAsStringNameValuePairs complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CDSOutputAsStringNameValuePairs">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:hl7-org:cdsoutput:r2}CDSOutput">
 *       &lt;sequence>
 *         &lt;element name="stringNameValuePair" type="{urn:hl7-org:vmr:r2}StringNameValuePair" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CDSOutputAsStringNameValuePairs", propOrder = {
    "stringNameValuePair"
})
public class CDSOutputAsStringNameValuePairs
    extends CDSOutput
{

    @XmlElement(required = true)
    protected List<StringNameValuePair> stringNameValuePair;

    /**
     * Gets the value of the stringNameValuePair property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stringNameValuePair property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStringNameValuePair().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StringNameValuePair }
     * 
     * 
     */
    public List<StringNameValuePair> getStringNameValuePair() {
        if (stringNameValuePair == null) {
            stringNameValuePair = new ArrayList<StringNameValuePair>();
        }
        return this.stringNameValuePair;
    }

}
