//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.30 at 06:15:10 PM PDT 
//


package org.hl7.kaoutput.r1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CDSExecutionMessageReason.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CDSExecutionMessageReason">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="DataFormatNotRecognized"/>
 *     &lt;enumeration value="DataValueIsOutOfRange"/>
 *     &lt;enumeration value="DataIsMissing"/>
 *     &lt;enumeration value="KnowledgeModuleIsNotCurrent"/>
 *     &lt;enumeration value="KnowledgeModuleIsNotApplicable"/>
 *     &lt;enumeration value="ResourceIssuedMessage"/>
 *     &lt;enumeration value="AuthenticationCredentialsNearingExpiry"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CDSExecutionMessageReason")
@XmlEnum
public enum CDSExecutionMessageReason {


    /**
     * 
     * 						The format in which the patient data was sent
     * 						was
     * 						not recognized. This may include
     * 						non-conformance to a VMR template.
     * 					
     * 
     */
    @XmlEnumValue("DataFormatNotRecognized")
    DATA_FORMAT_NOT_RECOGNIZED("DataFormatNotRecognized"),

    /**
     * 
     * 						Value for data item is out of expected range.
     * 					
     * 
     */
    @XmlEnumValue("DataValueIsOutOfRange")
    DATA_VALUE_IS_OUT_OF_RANGE("DataValueIsOutOfRange"),

    /**
     * 
     * 						Data item or value for a data item property is
     * 						missing.
     * 					
     * 
     */
    @XmlEnumValue("DataIsMissing")
    DATA_IS_MISSING("DataIsMissing"),

    /**
     * 
     * 						A knowledge module is not current and has been
     * 						superceded by a new version.
     * 					
     * 
     */
    @XmlEnumValue("KnowledgeModuleIsNotCurrent")
    KNOWLEDGE_MODULE_IS_NOT_CURRENT("KnowledgeModuleIsNotCurrent"),

    /**
     * 
     * 						The requested knowledge module is not applicable
     * 						to the given context - i.e., patient, care
     * 						location, encounter,
     * 						user, or recipient.
     * 					
     * 
     */
    @XmlEnumValue("KnowledgeModuleIsNotApplicable")
    KNOWLEDGE_MODULE_IS_NOT_APPLICABLE("KnowledgeModuleIsNotApplicable"),

    /**
     * 
     * 						A message that was issued by another resource (e.g.,
     * 						terminology server).
     * 					
     * 
     */
    @XmlEnumValue("ResourceIssuedMessage")
    RESOURCE_ISSUED_MESSAGE("ResourceIssuedMessage"),

    /**
     * The credentials used for establishing
     * 						connectivity will expire in the near future.
     * 					
     * 
     */
    @XmlEnumValue("AuthenticationCredentialsNearingExpiry")
    AUTHENTICATION_CREDENTIALS_NEARING_EXPIRY("AuthenticationCredentialsNearingExpiry");
    private final String value;

    CDSExecutionMessageReason(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CDSExecutionMessageReason fromValue(String v) {
        for (CDSExecutionMessageReason c: CDSExecutionMessageReason.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
