//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.26 at 04:33:53 PM PDT 
//

package org.hl7.cdsinput.r2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import org.hl7.cdsdt.r2.CD;
import org.hl7.vmr.r2.CodedIdentifier;
import org.hl7.vmr.r2.NameValuePair;
import org.hl7.vmr.r2.Organization;
import org.hl7.vmr.r2.Person;

/**
 * The situation or context within which a CDS evaluation is made. Included in
 * CDS inputs for HL7 Context-Aware Knowledge Retrieval (Infobutton) Knowledge
 * Request standard. Used, for example, to generate human-readable care guidance
 * in the end-user's preferred language.
 * 
 * <p>
 * Java class for CDSContext complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="CDSContext">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="templateId" type="{urn:hl7-org:vmr:r2}CodedIdentifier" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="cdsInitiatingOrganization" type="{urn:hl7-org:vmr:r2}Organization" minOccurs="0"/>
 *         &lt;element name="cdsInitiatingPerson" type="{urn:hl7-org:vmr:r2}Person" minOccurs="0"/>
 *         &lt;element name="cdsSystemUserType" type="{urn:hl7-org:cdsdt:r2}CD" minOccurs="0"/>
 *         &lt;element name="cdsSystemUserPreferredLanguage" type="{urn:hl7-org:cdsdt:r2}CD" minOccurs="0"/>
 *         &lt;element name="cdsSystemUserTaskContext" type="{urn:hl7-org:cdsdt:r2}CD" minOccurs="0"/>
 *         &lt;element name="cdsReceivingOrganization" type="{urn:hl7-org:vmr:r2}Organization" minOccurs="0"/>
 *         &lt;element name="cdsReceivingPerson" type="{urn:hl7-org:vmr:r2}Person" minOccurs="0"/>
 *         &lt;element name="cdsInformationRecipientType" type="{urn:hl7-org:cdsdt:r2}CD" minOccurs="0"/>
 *         &lt;element name="cdsInformationRecipientPreferredLanguage" type="{urn:hl7-org:cdsdt:r2}CD" minOccurs="0"/>
 *         &lt;element name="cdsEncounterType" type="{urn:hl7-org:cdsdt:r2}CD" minOccurs="0"/>
 *         &lt;element name="cdsSubTopic" type="{urn:hl7-org:cdsdt:r2}CD" minOccurs="0"/>
 *         &lt;element name="extension" type="{urn:hl7-org:vmr:r2}NameValuePair" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CDSContext", propOrder = {
    "templateId", "cdsInitiatingOrganization", "cdsInitiatingPerson",
    "cdsSystemUserType", "cdsSystemUserPreferredLanguage",
    "cdsSystemUserTaskContext", "cdsReceivingOrganization",
    "cdsReceivingPerson", "cdsInformationRecipientType",
    "cdsInformationRecipientPreferredLanguage", "cdsEncounterType",
    "cdsSubTopic", "extension"
})
public class CDSContext {

  protected List<CodedIdentifier> templateId;

  protected Organization cdsInitiatingOrganization;

  protected Person cdsInitiatingPerson;

  protected CD cdsSystemUserType;

  protected CD cdsSystemUserPreferredLanguage;

  protected CD cdsSystemUserTaskContext;

  protected Organization cdsReceivingOrganization;

  protected Person cdsReceivingPerson;

  protected CD cdsInformationRecipientType;

  protected CD cdsInformationRecipientPreferredLanguage;

  protected CD cdsEncounterType;

  protected CD cdsSubTopic;

  protected List<NameValuePair> extension;

  /**
   * Gets the value of the templateId property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot.
   * Therefore any modification you make to the returned list will be present
   * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
   * for the templateId property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
   * getTemplateId().add(newItem);
   * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link CodedIdentifier }
   * 
   * 
   */
  public List<CodedIdentifier> getTemplateId() {
    if (templateId == null) {
      templateId = new ArrayList<CodedIdentifier>();
    }
    return this.templateId;
  }

  /**
   * Gets the value of the cdsInitiatingOrganization property.
   * 
   * @return possible object is {@link Organization }
   * 
   */
  public Organization getCdsInitiatingOrganization() {
    return cdsInitiatingOrganization;
  }

  /**
   * Sets the value of the cdsInitiatingOrganization property.
   * 
   * @param value allowed object is {@link Organization }
   * 
   */
  public void setCdsInitiatingOrganization(Organization value) {
    this.cdsInitiatingOrganization = value;
  }

  /**
   * Gets the value of the cdsInitiatingPerson property.
   * 
   * @return possible object is {@link Person }
   * 
   */
  public Person getCdsInitiatingPerson() {
    return cdsInitiatingPerson;
  }

  /**
   * Sets the value of the cdsInitiatingPerson property.
   * 
   * @param value allowed object is {@link Person }
   * 
   */
  public void setCdsInitiatingPerson(Person value) {
    this.cdsInitiatingPerson = value;
  }

  /**
   * Gets the value of the cdsSystemUserType property.
   * 
   * @return possible object is {@link CD }
   * 
   */
  public CD getCdsSystemUserType() {
    return cdsSystemUserType;
  }

  /**
   * Sets the value of the cdsSystemUserType property.
   * 
   * @param value allowed object is {@link CD }
   * 
   */
  public void setCdsSystemUserType(CD value) {
    this.cdsSystemUserType = value;
  }

  /**
   * Gets the value of the cdsSystemUserPreferredLanguage property.
   * 
   * @return possible object is {@link CD }
   * 
   */
  public CD getCdsSystemUserPreferredLanguage() {
    return cdsSystemUserPreferredLanguage;
  }

  /**
   * Sets the value of the cdsSystemUserPreferredLanguage property.
   * 
   * @param value allowed object is {@link CD }
   * 
   */
  public void setCdsSystemUserPreferredLanguage(CD value) {
    this.cdsSystemUserPreferredLanguage = value;
  }

  /**
   * Gets the value of the cdsSystemUserTaskContext property.
   * 
   * @return possible object is {@link CD }
   * 
   */
  public CD getCdsSystemUserTaskContext() {
    return cdsSystemUserTaskContext;
  }

  /**
   * Sets the value of the cdsSystemUserTaskContext property.
   * 
   * @param value allowed object is {@link CD }
   * 
   */
  public void setCdsSystemUserTaskContext(CD value) {
    this.cdsSystemUserTaskContext = value;
  }

  /**
   * Gets the value of the cdsReceivingOrganization property.
   * 
   * @return possible object is {@link Organization }
   * 
   */
  public Organization getCdsReceivingOrganization() {
    return cdsReceivingOrganization;
  }

  /**
   * Sets the value of the cdsReceivingOrganization property.
   * 
   * @param value allowed object is {@link Organization }
   * 
   */
  public void setCdsReceivingOrganization(Organization value) {
    this.cdsReceivingOrganization = value;
  }

  /**
   * Gets the value of the cdsReceivingPerson property.
   * 
   * @return possible object is {@link Person }
   * 
   */
  public Person getCdsReceivingPerson() {
    return cdsReceivingPerson;
  }

  /**
   * Sets the value of the cdsReceivingPerson property.
   * 
   * @param value allowed object is {@link Person }
   * 
   */
  public void setCdsReceivingPerson(Person value) {
    this.cdsReceivingPerson = value;
  }

  /**
   * Gets the value of the cdsInformationRecipientType property.
   * 
   * @return possible object is {@link CD }
   * 
   */
  public CD getCdsInformationRecipientType() {
    return cdsInformationRecipientType;
  }

  /**
   * Sets the value of the cdsInformationRecipientType property.
   * 
   * @param value allowed object is {@link CD }
   * 
   */
  public void setCdsInformationRecipientType(CD value) {
    this.cdsInformationRecipientType = value;
  }

  /**
   * Gets the value of the cdsInformationRecipientPreferredLanguage property.
   * 
   * @return possible object is {@link CD }
   * 
   */
  public CD getCdsInformationRecipientPreferredLanguage() {
    return cdsInformationRecipientPreferredLanguage;
  }

  /**
   * Sets the value of the cdsInformationRecipientPreferredLanguage property.
   * 
   * @param value allowed object is {@link CD }
   * 
   */
  public void setCdsInformationRecipientPreferredLanguage(CD value) {
    this.cdsInformationRecipientPreferredLanguage = value;
  }

  /**
   * Gets the value of the cdsEncounterType property.
   * 
   * @return possible object is {@link CD }
   * 
   */
  public CD getCdsEncounterType() {
    return cdsEncounterType;
  }

  /**
   * Sets the value of the cdsEncounterType property.
   * 
   * @param value allowed object is {@link CD }
   * 
   */
  public void setCdsEncounterType(CD value) {
    this.cdsEncounterType = value;
  }

  /**
   * Gets the value of the cdsSubTopic property.
   * 
   * @return possible object is {@link CD }
   * 
   */
  public CD getCdsSubTopic() {
    return cdsSubTopic;
  }

  /**
   * Sets the value of the cdsSubTopic property.
   * 
   * @param value allowed object is {@link CD }
   * 
   */
  public void setCdsSubTopic(CD value) {
    this.cdsSubTopic = value;
  }

  /**
   * Gets the value of the extension property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot.
   * Therefore any modification you make to the returned list will be present
   * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
   * for the extension property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
   * getExtension().add(newItem);
   * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link NameValuePair }
   * 
   * 
   */
  public List<NameValuePair> getExtension() {
    if (extension == null) {
      extension = new ArrayList<NameValuePair>();
    }
    return this.extension;
  }

}
