//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.26 at 04:34:25 PM PDT 
//

package org.hl7.cdsdt.r2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * A CD is a reference to a concept defined in an external code system,
 * terminology, or ontology.
 * 
 * A CD may also contain an original text or phrase that served as the basis of
 * the coding.
 * 
 * <p>
 * Java class for CD complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="CD">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:hl7-org:cdsdt:r2}ANY">
 *       &lt;sequence>
 *         &lt;element name="displayName" type="{urn:hl7-org:cdsdt:r2}ST" minOccurs="0"/>
 *         &lt;element name="originalText" type="{urn:hl7-org:cdsdt:r2}ST" minOccurs="0"/>
 *         &lt;element name="translation" type="{urn:hl7-org:cdsdt:r2}CD" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="code" type="{urn:hl7-org:cdsdt:r2}Code" />
 *       &lt;attribute name="codeSystem" type="{urn:hl7-org:cdsdt:r2}Uid" />
 *       &lt;attribute name="codeSystemName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="codeSystemVersion" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="valueSet" type="{urn:hl7-org:cdsdt:r2}Uid" />
 *       &lt;attribute name="valueSetVersion" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CD", propOrder = {
    "displayName", "originalText", "translation"
})
public class CD extends ANY {

  protected ST displayName;

  protected ST originalText;

  protected List<CD> translation;

  @XmlAttribute(name = "code")
  protected String code;

  @XmlAttribute(name = "codeSystem")
  protected String codeSystem;

  @XmlAttribute(name = "codeSystemName")
  protected String codeSystemName;

  @XmlAttribute(name = "codeSystemVersion")
  protected String codeSystemVersion;

  @XmlAttribute(name = "valueSet")
  protected String valueSet;

  @XmlAttribute(name = "valueSetVersion")
  protected String valueSetVersion;

  /**
   * Gets the value of the displayName property.
   * 
   * @return possible object is {@link ST }
   * 
   */
  public ST getDisplayName() {
    return displayName;
  }

  /**
   * Sets the value of the displayName property.
   * 
   * @param value allowed object is {@link ST }
   * 
   */
  public void setDisplayName(ST value) {
    this.displayName = value;
  }

  /**
   * Gets the value of the originalText property.
   * 
   * @return possible object is {@link ST }
   * 
   */
  public ST getOriginalText() {
    return originalText;
  }

  /**
   * Sets the value of the originalText property.
   * 
   * @param value allowed object is {@link ST }
   * 
   */
  public void setOriginalText(ST value) {
    this.originalText = value;
  }

  /**
   * Gets the value of the translation property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot.
   * Therefore any modification you make to the returned list will be present
   * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
   * for the translation property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
   * getTranslation().add(newItem);
   * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list {@link CD }
   * 
   * 
   */
  public List<CD> getTranslation() {
    if (translation == null) {
      translation = new ArrayList<CD>();
    }
    return this.translation;
  }

  /**
   * Gets the value of the code property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getCode() {
    return code;
  }

  /**
   * Sets the value of the code property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setCode(String value) {
    this.code = value;
  }

  /**
   * Gets the value of the codeSystem property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getCodeSystem() {
    return codeSystem;
  }

  /**
   * Sets the value of the codeSystem property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setCodeSystem(String value) {
    this.codeSystem = value;
  }

  /**
   * Gets the value of the codeSystemName property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getCodeSystemName() {
    return codeSystemName;
  }

  /**
   * Sets the value of the codeSystemName property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setCodeSystemName(String value) {
    this.codeSystemName = value;
  }

  /**
   * Gets the value of the codeSystemVersion property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getCodeSystemVersion() {
    return codeSystemVersion;
  }

  /**
   * Sets the value of the codeSystemVersion property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setCodeSystemVersion(String value) {
    this.codeSystemVersion = value;
  }

  /**
   * Gets the value of the valueSet property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getValueSet() {
    return valueSet;
  }

  /**
   * Sets the value of the valueSet property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setValueSet(String value) {
    this.valueSet = value;
  }

  /**
   * Gets the value of the valueSetVersion property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getValueSetVersion() {
    return valueSetVersion;
  }

  /**
   * Sets the value of the valueSetVersion property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setValueSetVersion(String value) {
    this.valueSetVersion = value;
  }

}
