//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.26 at 04:34:25 PM PDT 
//

package org.hl7.cdsdt.r2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * Represents data where coded values are associated with a specific order.
 * 
 * Note: CO may be used for things that model rankings and scores, e.g. likert
 * scales, pain, Apgar values, etc, where there is a) implied ordering, b) no
 * implication that the distance between each value is constant, and c) the
 * total number of values is finite. CO may also be used in the context of an
 * ordered code system. In this case, it may not be appropriate or even possible
 * to use the value attribute, but CO may still be used so that models that make
 * use of such code systems may introduce model elements that involve statements
 * about the order of the terms in a domain.
 * 
 * The relative order of values in a code system need not be independently
 * obvious in the literal representation of the CO. It these circumstances, is
 * expected that an application will look up the ordering of these values from
 * some definition of the code system.
 * 
 * Some of the code systems will directly assign numerical value to the concepts
 * that are suitable for some mathemetical operations.
 * 
 * Though it would generally make sense, applications SHOULD not assume that the
 * translations of the code, if provided, will have the same ordering as the CO.
 * Translations SHALL not be considered when the ordering of the code system is
 * determined.
 * 
 * <p>
 * Java class for CO complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="CO">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:hl7-org:cdsdt:r2}QTY">
 *       &lt;sequence>
 *         &lt;element name="code" type="{urn:hl7-org:cdsdt:r2}CD" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="value" type="{urn:hl7-org:cdsdt:r2}Decimal" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CO", propOrder = {
  "code"
})
public class CO extends QTY {

  protected CD code;

  @XmlAttribute(name = "value")
  protected Double value;

  /**
   * Gets the value of the code property.
   * 
   * @return possible object is {@link CD }
   * 
   */
  public CD getCode() {
    return code;
  }

  /**
   * Sets the value of the code property.
   * 
   * @param value allowed object is {@link CD }
   * 
   */
  public void setCode(CD value) {
    this.code = value;
  }

  /**
   * Gets the value of the value property.
   * 
   * @return possible object is {@link Double }
   * 
   */
  public Double getValue() {
    return value;
  }

  /**
   * Sets the value of the value property.
   * 
   * @param value allowed object is {@link Double }
   * 
   */
  public void setValue(Double value) {
    this.value = value;
  }

}
