//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.26 at 04:34:25 PM PDT 
//

package org.hl7.cdsdt.r2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * Data that is primarily intended for human interpretation or for further
 * machine processing outside the scope of this specification. This includes
 * unformatted or formatted written language, multimedia data, or structured
 * information as defined by a different standard (e.g., XML-signatures.)
 * Encapsulated data can be present in two forms, inline or by reference. The
 * content is the same whether it is located inline or remote. Inline data is
 * communicated or moved as part of the encapsulated data value, whereas
 * by-reference data may reside at a different location: a URL/URI that provides
 * reference to the information required to locate the data. Inline data may be
 * provided in one of 3 different ways:
 * 
 * 1) as a plain sequence of characters (value) 2) as a binary (a sequence of
 * bytes) (data 3) as xml content (xml)
 * 
 * Content SHALL be provided if the ED has no nullFlavor. The content may be
 * provided in-line (using only one of value, data or xml), or it may be
 * provided as a reference.Content may be provided in-line and a reference also
 * may be given; in these cases, it is expected that the content of the
 * reference will be exactly the same as the in-line content. Information
 * Processing Entities are not required to check this, but may regard it as an
 * error condition if the content does not match
 * 
 * <p>
 * Java class for ED complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ED">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:hl7-org:cdsdt:r2}ANY">
 *       &lt;sequence>
 *         &lt;element name="data" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *         &lt;element name="xml" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="reference" type="{urn:hl7-org:cdsdt:r2}TEL" minOccurs="0"/>
 *         &lt;element name="integrityCheck" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *         &lt;element name="description" type="{urn:hl7-org:cdsdt:r2}ST" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="mediaType" type="{urn:hl7-org:cdsdt:r2}Code" default="text/plain" />
 *       &lt;attribute name="charset" type="{urn:hl7-org:cdsdt:r2}Code" />
 *       &lt;attribute name="language" type="{urn:hl7-org:cdsdt:r2}Code" />
 *       &lt;attribute name="compression" type="{urn:hl7-org:cdsdt:r2}Compression" />
 *       &lt;attribute name="integrityCheckAlgorithm" type="{urn:hl7-org:cdsdt:r2}IntegrityCheckAlgorithm" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ED", propOrder = {
    "data", "xml", "reference", "integrityCheck", "description"
})
public class ED extends ANY {

  protected byte[] data;

  protected Object xml;

  protected TEL reference;

  protected byte[] integrityCheck;

  protected ST description;

  @XmlAttribute(name = "value")
  protected String value;

  @XmlAttribute(name = "mediaType")
  protected String mediaType;

  @XmlAttribute(name = "charset")
  protected String charset;

  @XmlAttribute(name = "language")
  protected String language;

  @XmlAttribute(name = "compression")
  protected Compression compression;

  @XmlAttribute(name = "integrityCheckAlgorithm")
  protected IntegrityCheckAlgorithm integrityCheckAlgorithm;

  /**
   * Gets the value of the data property.
   * 
   * @return possible object is byte[]
   */
  public byte[] getData() {
    return data;
  }

  /**
   * Sets the value of the data property.
   * 
   * @param value allowed object is byte[]
   */
  public void setData(byte[] value) {
    this.data = value;
  }

  /**
   * Gets the value of the xml property.
   * 
   * @return possible object is {@link Object }
   * 
   */
  public Object getXml() {
    return xml;
  }

  /**
   * Sets the value of the xml property.
   * 
   * @param value allowed object is {@link Object }
   * 
   */
  public void setXml(Object value) {
    this.xml = value;
  }

  /**
   * Gets the value of the reference property.
   * 
   * @return possible object is {@link TEL }
   * 
   */
  public TEL getReference() {
    return reference;
  }

  /**
   * Sets the value of the reference property.
   * 
   * @param value allowed object is {@link TEL }
   * 
   */
  public void setReference(TEL value) {
    this.reference = value;
  }

  /**
   * Gets the value of the integrityCheck property.
   * 
   * @return possible object is byte[]
   */
  public byte[] getIntegrityCheck() {
    return integrityCheck;
  }

  /**
   * Sets the value of the integrityCheck property.
   * 
   * @param value allowed object is byte[]
   */
  public void setIntegrityCheck(byte[] value) {
    this.integrityCheck = value;
  }

  /**
   * Gets the value of the description property.
   * 
   * @return possible object is {@link ST }
   * 
   */
  public ST getDescription() {
    return description;
  }

  /**
   * Sets the value of the description property.
   * 
   * @param value allowed object is {@link ST }
   * 
   */
  public void setDescription(ST value) {
    this.description = value;
  }

  /**
   * Gets the value of the value property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getValue() {
    return value;
  }

  /**
   * Sets the value of the value property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setValue(String value) {
    this.value = value;
  }

  /**
   * Gets the value of the mediaType property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getMediaType() {
    if (mediaType == null) {
      return "text/plain";
    } else {
      return mediaType;
    }
  }

  /**
   * Sets the value of the mediaType property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setMediaType(String value) {
    this.mediaType = value;
  }

  /**
   * Gets the value of the charset property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getCharset() {
    return charset;
  }

  /**
   * Sets the value of the charset property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setCharset(String value) {
    this.charset = value;
  }

  /**
   * Gets the value of the language property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getLanguage() {
    return language;
  }

  /**
   * Sets the value of the language property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setLanguage(String value) {
    this.language = value;
  }

  /**
   * Gets the value of the compression property.
   * 
   * @return possible object is {@link Compression }
   * 
   */
  public Compression getCompression() {
    return compression;
  }

  /**
   * Sets the value of the compression property.
   * 
   * @param value allowed object is {@link Compression }
   * 
   */
  public void setCompression(Compression value) {
    this.compression = value;
  }

  /**
   * Gets the value of the integrityCheckAlgorithm property.
   * 
   * @return possible object is {@link IntegrityCheckAlgorithm }
   * 
   */
  public IntegrityCheckAlgorithm getIntegrityCheckAlgorithm() {
    return integrityCheckAlgorithm;
  }

  /**
   * Sets the value of the integrityCheckAlgorithm property.
   * 
   * @param value allowed object is {@link IntegrityCheckAlgorithm }
   * 
   */
  public void setIntegrityCheckAlgorithm(IntegrityCheckAlgorithm value) {
    this.integrityCheckAlgorithm = value;
  }

}
