//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.30 at 06:15:10 PM PDT 
//


package org.hl7.knowledgeartifact.r1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import org.hl7.cdsdt.r2.II;


/**
 * Actions are the output of the CDS system and
 * 				represent the tasks that must be carried out by a human or a
 * 				computer system.
 * 			
 * 
 * <p>Java class for ActionBase complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ActionBase">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="actionId" type="{urn:hl7-org:cdsdt:r2}II" minOccurs="0"/>
 *         &lt;element name="supportingEvidence" type="{urn:hl7-org:knowledgeartifact:r1}SupportingEvidence" minOccurs="0"/>
 *         &lt;element name="supportingResources" type="{urn:hl7-org:knowledgeartifact:r1}SupportingResource" minOccurs="0"/>
 *         &lt;element name="actors" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="actor" type="{urn:hl7-org:knowledgeartifact:r1}Actor" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="behaviors" type="{urn:hl7-org:knowledgeartifact:r1}Behaviors" minOccurs="0"/>
 *         &lt;element name="conditions" type="{urn:hl7-org:knowledgeartifact:r1}Conditions" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ActionBase", propOrder = {
    "actionId",
    "supportingEvidence",
    "supportingResources",
    "actors",
    "behaviors",
    "conditions"
})
@XmlSeeAlso({
    ActionRef.class,
    AtomicAction.class,
    ActionGroup.class
})
public abstract class ActionBase {

    protected II actionId;
    protected SupportingEvidence supportingEvidence;
    protected SupportingResource supportingResources;
    protected ActionBase.Actors actors;
    protected Behaviors behaviors;
    protected Conditions conditions;

    /**
     * Gets the value of the actionId property.
     * 
     * @return
     *     possible object is
     *     {@link II }
     *     
     */
    public II getActionId() {
        return actionId;
    }

    /**
     * Sets the value of the actionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link II }
     *     
     */
    public void setActionId(II value) {
        this.actionId = value;
    }

    /**
     * Gets the value of the supportingEvidence property.
     * 
     * @return
     *     possible object is
     *     {@link SupportingEvidence }
     *     
     */
    public SupportingEvidence getSupportingEvidence() {
        return supportingEvidence;
    }

    /**
     * Sets the value of the supportingEvidence property.
     * 
     * @param value
     *     allowed object is
     *     {@link SupportingEvidence }
     *     
     */
    public void setSupportingEvidence(SupportingEvidence value) {
        this.supportingEvidence = value;
    }

    /**
     * Gets the value of the supportingResources property.
     * 
     * @return
     *     possible object is
     *     {@link SupportingResource }
     *     
     */
    public SupportingResource getSupportingResources() {
        return supportingResources;
    }

    /**
     * Sets the value of the supportingResources property.
     * 
     * @param value
     *     allowed object is
     *     {@link SupportingResource }
     *     
     */
    public void setSupportingResources(SupportingResource value) {
        this.supportingResources = value;
    }

    /**
     * Gets the value of the actors property.
     * 
     * @return
     *     possible object is
     *     {@link ActionBase.Actors }
     *     
     */
    public ActionBase.Actors getActors() {
        return actors;
    }

    /**
     * Sets the value of the actors property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionBase.Actors }
     *     
     */
    public void setActors(ActionBase.Actors value) {
        this.actors = value;
    }

    /**
     * Gets the value of the behaviors property.
     * 
     * @return
     *     possible object is
     *     {@link Behaviors }
     *     
     */
    public Behaviors getBehaviors() {
        return behaviors;
    }

    /**
     * Sets the value of the behaviors property.
     * 
     * @param value
     *     allowed object is
     *     {@link Behaviors }
     *     
     */
    public void setBehaviors(Behaviors value) {
        this.behaviors = value;
    }

    /**
     * Gets the value of the conditions property.
     * 
     * @return
     *     possible object is
     *     {@link Conditions }
     *     
     */
    public Conditions getConditions() {
        return conditions;
    }

    /**
     * Sets the value of the conditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Conditions }
     *     
     */
    public void setConditions(Conditions value) {
        this.conditions = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="actor" type="{urn:hl7-org:knowledgeartifact:r1}Actor" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "actor"
    })
    public static class Actors {

        @XmlElement(required = true)
        protected List<Actor> actor;

        /**
         * Gets the value of the actor property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the actor property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getActor().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Actor }
         * 
         * 
         */
        public List<Actor> getActor() {
            if (actor == null) {
                actor = new ArrayList<Actor>();
            }
            return this.actor;
        }

    }

}
