//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.30 at 06:15:10 PM PDT 
//


package org.hl7.knowledgeartifact.r1;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.hl7.cdsdt.r2.CD;
import org.hl7.cdsdt.r2.ST;


/**
 * This type of action is used to organize a group of
 * 				related actions into one container.
 * 
 * 				The semantics of how the group's
 * 				subelements interact with which each
 * 				other and how the subelements
 * 				might be presented are specified in
 * 				the group behavior.
 * 			
 * 
 * <p>Java class for ActionGroup complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ActionGroup">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:hl7-org:knowledgeartifact:r1}ActionBase">
 *       &lt;sequence>
 *         &lt;element name="title" type="{urn:hl7-org:cdsdt:r2}ST" minOccurs="0"/>
 *         &lt;element name="description" type="{urn:hl7-org:cdsdt:r2}ST" minOccurs="0"/>
 *         &lt;element name="representedConcepts" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="concept" type="{urn:hl7-org:cdsdt:r2}CD" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="subElements">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;choice maxOccurs="unbounded">
 *                     &lt;element name="simpleAction" type="{urn:hl7-org:knowledgeartifact:r1}AtomicAction"/>
 *                     &lt;element name="actionGroup" type="{urn:hl7-org:knowledgeartifact:r1}ActionGroup"/>
 *                     &lt;element name="actionRef" type="{urn:hl7-org:knowledgeartifact:r1}ActionRef"/>
 *                   &lt;/choice>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ActionGroup", propOrder = {
    "title",
    "description",
    "representedConcepts",
    "subElements"
})
public class ActionGroup
    extends ActionBase
{

    protected ST title;
    protected ST description;
    protected ActionGroup.RepresentedConcepts representedConcepts;
    @XmlElement(required = true)
    protected ActionGroup.SubElements subElements;

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link ST }
     *     
     */
    public ST getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link ST }
     *     
     */
    public void setTitle(ST value) {
        this.title = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link ST }
     *     
     */
    public ST getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link ST }
     *     
     */
    public void setDescription(ST value) {
        this.description = value;
    }

    /**
     * Gets the value of the representedConcepts property.
     * 
     * @return
     *     possible object is
     *     {@link ActionGroup.RepresentedConcepts }
     *     
     */
    public ActionGroup.RepresentedConcepts getRepresentedConcepts() {
        return representedConcepts;
    }

    /**
     * Sets the value of the representedConcepts property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionGroup.RepresentedConcepts }
     *     
     */
    public void setRepresentedConcepts(ActionGroup.RepresentedConcepts value) {
        this.representedConcepts = value;
    }

    /**
     * Gets the value of the subElements property.
     * 
     * @return
     *     possible object is
     *     {@link ActionGroup.SubElements }
     *     
     */
    public ActionGroup.SubElements getSubElements() {
        return subElements;
    }

    /**
     * Sets the value of the subElements property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionGroup.SubElements }
     *     
     */
    public void setSubElements(ActionGroup.SubElements value) {
        this.subElements = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="concept" type="{urn:hl7-org:cdsdt:r2}CD" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "concept"
    })
    public static class RepresentedConcepts {

        @XmlElement(required = true)
        protected List<CD> concept;

        /**
         * Gets the value of the concept property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the concept property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getConcept().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CD }
         * 
         * 
         */
        public List<CD> getConcept() {
            if (concept == null) {
                concept = new ArrayList<CD>();
            }
            return this.concept;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;choice maxOccurs="unbounded">
     *           &lt;element name="simpleAction" type="{urn:hl7-org:knowledgeartifact:r1}AtomicAction"/>
     *           &lt;element name="actionGroup" type="{urn:hl7-org:knowledgeartifact:r1}ActionGroup"/>
     *           &lt;element name="actionRef" type="{urn:hl7-org:knowledgeartifact:r1}ActionRef"/>
     *         &lt;/choice>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "simpleActionOrActionGroupOrActionRef"
    })
    public static class SubElements {

        @XmlElements({
            @XmlElement(name = "simpleAction", type = AtomicAction.class),
            @XmlElement(name = "actionGroup", type = ActionGroup.class),
            @XmlElement(name = "actionRef", type = ActionRef.class)
        })
        protected List<ActionBase> simpleActionOrActionGroupOrActionRef;

        /**
         * Gets the value of the simpleActionOrActionGroupOrActionRef property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the simpleActionOrActionGroupOrActionRef property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSimpleActionOrActionGroupOrActionRef().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AtomicAction }
         * {@link ActionGroup }
         * {@link ActionRef }
         * 
         * 
         */
        public List<ActionBase> getSimpleActionOrActionGroupOrActionRef() {
            if (simpleActionOrActionGroupOrActionRef == null) {
                simpleActionOrActionGroupOrActionRef = new ArrayList<ActionBase>();
            }
            return this.simpleActionOrActionGroupOrActionRef;
        }

    }

}
