//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.30 at 06:15:10 PM PDT 
//


package org.hl7.knowledgeartifact.r1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ArtifactType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ArtifactType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Rule"/>
 *     &lt;enumeration value="Order Set"/>
 *     &lt;enumeration value="Documentation Template"/>
 *     &lt;enumeration value="Library"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ArtifactType")
@XmlEnum
public enum ArtifactType {


    /**
     * Denotes an Event-Condition-Action Rule.  An ECA rule has a specific structure that is a restriction on the general structure of a CDS Knowledge Artifact.  See the Implementation Guide for the constraints applicable to ECA rules.
     * 
     */
    @XmlEnumValue("Rule")
    RULE("Rule"),

    /**
     * Denotes an Order Set for use by physicians at the point of care.  An Order Set has a specific structure that is a restriction on the general structure of a CDS Knowledge Artifact.  See the Implementation Guide for the constraints applicable to Order Sets.
     * 
     */
    @XmlEnumValue("Order Set")
    ORDER_SET("Order Set"),

    /**
     * Denotes a Documentation Template for use by care providers.  A Documentation Template has a specific structure that is a restriction on the general structure of a CDS Knowledge Artifact.  See the Implementation Guide for the constraints applicable to Documentation Templates.
     * 
     */
    @XmlEnumValue("Documentation Template")
    DOCUMENTATION_TEMPLATE("Documentation Template"),

    /**
     * Denotes a Library of artifact components that can be reused by reference in other artifacts.
     * 
     */
    @XmlEnumValue("Library")
    LIBRARY("Library");
    private final String value;

    ArtifactType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ArtifactType fromValue(String v) {
        for (ArtifactType c: ArtifactType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
