//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.26 at 04:34:23 PM PDT 
//

package org.hl7.knowledgeartifact.r1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * The Begin operator returns the starting point of an interval.
 * 
 * If the beginning of the interval is open, this operator returns the Successor
 * of the defined beginning point of the interval.
 * 
 * If the beginning of the interval is closed, this operator returns the defined
 * beginning point of the interval if it is not null.
 * 
 * Otherwise, it returns the minimum value of the point type of the interval.
 * 
 * If the argument is null, the result is null.
 * 
 * <p>
 * Java class for Begin complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Begin">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:hl7-org:knowledgeartifact:r1}UnaryExpression">
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Begin")
public class Begin extends UnaryExpression {

}
