//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.30 at 06:15:10 PM PDT 
//


package org.hl7.knowledgeartifact.r1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DataEventType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DataEventType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="DataElementAdded"/>
 *     &lt;enumeration value="DataElementModified"/>
 *     &lt;enumeration value="DataElementRemoved"/>
 *     &lt;enumeration value="DataElementAccessed"/>
 *     &lt;enumeration value="DataElementAccessEnded"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DataEventType")
@XmlEnum
public enum DataEventType {

    @XmlEnumValue("DataElementAdded")
    DATA_ELEMENT_ADDED("DataElementAdded"),
    @XmlEnumValue("DataElementModified")
    DATA_ELEMENT_MODIFIED("DataElementModified"),
    @XmlEnumValue("DataElementRemoved")
    DATA_ELEMENT_REMOVED("DataElementRemoved"),
    @XmlEnumValue("DataElementAccessed")
    DATA_ELEMENT_ACCESSED("DataElementAccessed"),
    @XmlEnumValue("DataElementAccessEnded")
    DATA_ELEMENT_ACCESS_ENDED("DataElementAccessEnded");
    private final String value;

    DataEventType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DataEventType fromValue(String v) {
        for (DataEventType c: DataEventType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
