//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.30 at 06:15:10 PM PDT 
//


package org.hl7.knowledgeartifact.r1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The DateAdd operator adds numberOfPeriods date periods of the specified granularity to the given date.
 * 			
 * Note that this is different than adding an Interval to a date time, because for operations on granularities such as month and year, the interval is not well-defined due to varying month and year lengths. As a result, DateAdd is used to provide well-defined and consistent semantics for date arithmetic involving months and years. 
 * 
 * If any argument is null, the result is null.
 * 
 * <p>Java class for DateAdd complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DateAdd">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:hl7-org:knowledgeartifact:r1}Expression">
 *       &lt;sequence>
 *         &lt;element name="date" type="{urn:hl7-org:knowledgeartifact:r1}Expression"/>
 *         &lt;element name="granularity" type="{urn:hl7-org:knowledgeartifact:r1}Expression"/>
 *         &lt;element name="numberOfPeriods" type="{urn:hl7-org:knowledgeartifact:r1}Expression"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DateAdd", propOrder = {
    "date",
    "granularity",
    "numberOfPeriods"
})
public class DateAdd
    extends Expression
{

    @XmlElement(required = true)
    protected Expression date;
    @XmlElement(required = true)
    protected Expression granularity;
    @XmlElement(required = true)
    protected Expression numberOfPeriods;

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link Expression }
     *     
     */
    public Expression getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link Expression }
     *     
     */
    public void setDate(Expression value) {
        this.date = value;
    }

    /**
     * Gets the value of the granularity property.
     * 
     * @return
     *     possible object is
     *     {@link Expression }
     *     
     */
    public Expression getGranularity() {
        return granularity;
    }

    /**
     * Sets the value of the granularity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Expression }
     *     
     */
    public void setGranularity(Expression value) {
        this.granularity = value;
    }

    /**
     * Gets the value of the numberOfPeriods property.
     * 
     * @return
     *     possible object is
     *     {@link Expression }
     *     
     */
    public Expression getNumberOfPeriods() {
        return numberOfPeriods;
    }

    /**
     * Sets the value of the numberOfPeriods property.
     * 
     * @param value
     *     allowed object is
     *     {@link Expression }
     *     
     */
    public void setNumberOfPeriods(Expression value) {
        this.numberOfPeriods = value;
    }

}
