//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.26 at 04:34:23 PM PDT 
//

package org.hl7.knowledgeartifact.r1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for DateGranularity.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="DateGranularity">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Year"/>
 *     &lt;enumeration value="Month"/>
 *     &lt;enumeration value="Week"/>
 *     &lt;enumeration value="Day"/>
 *     &lt;enumeration value="Hour"/>
 *     &lt;enumeration value="Minute"/>
 *     &lt;enumeration value="Second"/>
 *     &lt;enumeration value="Millisecond"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DateGranularity")
@XmlEnum
public enum DateGranularity {

  @XmlEnumValue("Year")
  YEAR("Year"), @XmlEnumValue("Month")
  MONTH("Month"), @XmlEnumValue("Week")
  WEEK("Week"), @XmlEnumValue("Day")
  DAY("Day"), @XmlEnumValue("Hour")
  HOUR("Hour"), @XmlEnumValue("Minute")
  MINUTE("Minute"), @XmlEnumValue("Second")
  SECOND("Second"), @XmlEnumValue("Millisecond")
  MILLISECOND("Millisecond");
  private final String value;

  DateGranularity(String v) {
    value = v;
  }

  public String value() {
    return value;
  }

  public static DateGranularity fromValue(String v) {
    for (DateGranularity c : DateGranularity.values()) {
      if (c.value.equals(v)) {
        return c;
      }
    }
    throw new IllegalArgumentException(v);
  }

}
