//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.30 at 06:15:10 PM PDT 
//


package org.hl7.knowledgeartifact.r1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				The DeclareResponseAction provides a mechanism to declare a container for responses provided by the user
 * 				in response to CollectInformationActions. The intended semantics are to provide a container that can be
 * 				used to access responses within expressions used subsequently in an artifact.
 * 
 * 				The DeclareResponseAction creates a named container within the Parameters scope of the artifact, and expressions
 * 				may access the contents of a response using a ParameterRef expression.
 * 
 * 				The container is expected to be a collection of name-value pairs, and the intended semantics are to allow the
 * 				Property expression to be used, in connection with a ParameterRef expression as the source, to retrieve the current
 * 				value for a property.
 * 
 * 				The CollectInformationAction contains a responseBinding attribute that specifies the name of the container, and the
 * 				name of the property to be used to store the response value.
 * 
 * 				If no Name attribute is provided, the response container will be named Responses.
 * 			
 * 
 * <p>Java class for DeclareResponseAction complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DeclareResponseAction">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:hl7-org:knowledgeartifact:r1}AtomicAction">
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" default="Responses" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DeclareResponseAction")
public class DeclareResponseAction
    extends AtomicAction
{

    @XmlAttribute(name = "name")
    protected String name;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        if (name == null) {
            return "Responses";
        } else {
            return name;
        }
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
