//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.26 at 04:34:21 PM PDT 
//

package org.hl7.knowledgeartifact.r1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.hl7.cdsdt.r2.ENXP;
import org.hl7.cdsdt.r2.EntityNameUse;

/**
 * The EntityNameLiteral expression returns a value of type EN with the given
 * attributes.
 * 
 * <p>
 * Java class for EntityNameLiteral complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="EntityNameLiteral">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:hl7-org:knowledgeartifact:r1}Expression">
 *       &lt;sequence>
 *         &lt;element name="part" type="{urn:hl7-org:cdsdt:r2}ENXP" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="use" type="{urn:hl7-org:cdsdt:r2}set_EntityNameUse" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EntityNameLiteral", propOrder = {
  "part"
})
public class EntityNameLiteral extends Expression {

  @XmlElement(required = true)
  protected List<ENXP> part;

  @XmlAttribute(name = "use")
  protected List<EntityNameUse> use;

  /**
   * Gets the value of the part property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot.
   * Therefore any modification you make to the returned list will be present
   * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
   * for the part property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
   * getPart().add(newItem);
   * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list {@link ENXP }
   * 
   * 
   */
  public List<ENXP> getPart() {
    if (part == null) {
      part = new ArrayList<ENXP>();
    }
    return this.part;
  }

  /**
   * Gets the value of the use property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot.
   * Therefore any modification you make to the returned list will be present
   * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
   * for the use property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
   * getUse().add(newItem);
   * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link EntityNameUse }
   * 
   * 
   */
  public List<EntityNameUse> getUse() {
    if (use == null) {
      use = new ArrayList<EntityNameUse>();
    }
    return this.use;
  }

}
