//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.26 at 04:34:23 PM PDT 
//

package org.hl7.knowledgeartifact.r1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * The Equal operator returns true if the arguments are equal; and false
 * otherwise. Equality semantics are defined to be value-based.
 * 
 * For scalars this means that equality returns true if and only if the result
 * of each argument evaluates to the same value.
 * 
 * For object types, this means that equality returns true if and only if the
 * objects are of the same type, and the values for all properties are the same.
 * 
 * For list types, this means that equality returns true if and only if the
 * lists contain elements of the same type, have the same number of elements,
 * and for each element in the lists, in order, the elements are equal using the
 * same semantics.
 * 
 * For interval types, equality returns true if and only if the intervals are
 * over the same point type, and they have the same value for the beginning and
 * ending points of the interval.
 * 
 * If either argument is null, the result is null.
 * 
 * <p>
 * Java class for Equal complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Equal">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:hl7-org:knowledgeartifact:r1}BinaryExpression">
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Equal")
public class Equal extends BinaryExpression {

}
