//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.30 at 06:15:10 PM PDT 
//


package org.hl7.knowledgeartifact.r1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import org.hl7.cdsdt.r2.CD;


/**
 * Reference to research on which the artifact is
 * 				based. This evidence can be 'graded' depending on its quality and
 * 				pedigree and the strength of the recommendations it makes.
 * 			
 * 
 * <p>Java class for Evidence complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Evidence">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="qualityOfEvidence" type="{urn:hl7-org:cdsdt:r2}CD" minOccurs="0"/>
 *         &lt;element name="strengthOfRecommendation" type="{urn:hl7-org:cdsdt:r2}CD" minOccurs="0"/>
 *         &lt;element name="resources" type="{urn:hl7-org:knowledgeartifact:r1}SupportingResource" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Evidence", propOrder = {
    "qualityOfEvidence",
    "strengthOfRecommendation",
    "resources"
})
public class Evidence {

    protected CD qualityOfEvidence;
    protected CD strengthOfRecommendation;
    protected SupportingResource resources;

    /**
     * Gets the value of the qualityOfEvidence property.
     * 
     * @return
     *     possible object is
     *     {@link CD }
     *     
     */
    public CD getQualityOfEvidence() {
        return qualityOfEvidence;
    }

    /**
     * Sets the value of the qualityOfEvidence property.
     * 
     * @param value
     *     allowed object is
     *     {@link CD }
     *     
     */
    public void setQualityOfEvidence(CD value) {
        this.qualityOfEvidence = value;
    }

    /**
     * Gets the value of the strengthOfRecommendation property.
     * 
     * @return
     *     possible object is
     *     {@link CD }
     *     
     */
    public CD getStrengthOfRecommendation() {
        return strengthOfRecommendation;
    }

    /**
     * Sets the value of the strengthOfRecommendation property.
     * 
     * @param value
     *     allowed object is
     *     {@link CD }
     *     
     */
    public void setStrengthOfRecommendation(CD value) {
        this.strengthOfRecommendation = value;
    }

    /**
     * Gets the value of the resources property.
     * 
     * @return
     *     possible object is
     *     {@link SupportingResource }
     *     
     */
    public SupportingResource getResources() {
        return resources;
    }

    /**
     * Sets the value of the resources property.
     * 
     * @param value
     *     allowed object is
     *     {@link SupportingResource }
     *     
     */
    public void setResources(SupportingResource value) {
        this.resources = value;
    }

}
