//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.30 at 06:15:10 PM PDT 
//


package org.hl7.knowledgeartifact.r1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A constraint specified in the form of an
 * 				expression. The constraint type and the constraint expression
 * 				combine together to specify the full constraint. For example,
 * 				the constraint type specifies that the lower bound is being specified
 * 				and the expression provides the lower bound value.
 * 			
 * 
 * <p>Java class for ExpressionConstraint complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExpressionConstraint">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:hl7-org:knowledgeartifact:r1}RangeConstraint">
 *       &lt;sequence>
 *         &lt;element name="constraint" type="{urn:hl7-org:knowledgeartifact:r1}Expression"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExpressionConstraint", propOrder = {
    "constraint"
})
public class ExpressionConstraint
    extends RangeConstraint
{

    @XmlElement(required = true)
    protected Expression constraint;

    /**
     * Gets the value of the constraint property.
     * 
     * @return
     *     possible object is
     *     {@link Expression }
     *     
     */
    public Expression getConstraint() {
        return constraint;
    }

    /**
     * Sets the value of the constraint property.
     * 
     * @param value
     *     allowed object is
     *     {@link Expression }
     *     
     */
    public void setConstraint(Expression value) {
        this.constraint = value;
    }

}
