//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.26 at 04:34:23 PM PDT 
//

package org.hl7.knowledgeartifact.r1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * The Indexer operator returns the indexth element in a string or list.
 * 
 * Indexes in strings and lists are defined to be 1-based.
 * 
 * If either argument is null, the result is null.
 * 
 * <p>
 * Java class for Indexer complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Indexer">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:hl7-org:knowledgeartifact:r1}Expression">
 *       &lt;sequence>
 *         &lt;element name="operand" type="{urn:hl7-org:knowledgeartifact:r1}Expression"/>
 *         &lt;element name="index" type="{urn:hl7-org:knowledgeartifact:r1}Expression"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Indexer", propOrder = {
    "operand", "index"
})
public class Indexer extends Expression {

  @XmlElement(required = true)
  protected Expression operand;

  @XmlElement(required = true)
  protected Expression index;

  /**
   * Gets the value of the operand property.
   * 
   * @return possible object is {@link Expression }
   * 
   */
  public Expression getOperand() {
    return operand;
  }

  /**
   * Sets the value of the operand property.
   * 
   * @param value allowed object is {@link Expression }
   * 
   */
  public void setOperand(Expression value) {
    this.operand = value;
  }

  /**
   * Gets the value of the index property.
   * 
   * @return possible object is {@link Expression }
   * 
   */
  public Expression getIndex() {
    return index;
  }

  /**
   * Sets the value of the index property.
   * 
   * @param value allowed object is {@link Expression }
   * 
   */
  public void setIndex(Expression value) {
    this.index = value;
  }

}
