//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.26 at 04:34:23 PM PDT 
//

package org.hl7.knowledgeartifact.r1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;

/**
 * The ObjectDescriptor type allows arbitrary object descriptors to be built,
 * allowing for the creation of a value that has enough information to uniquely
 * identify an object, but is not the object itself. Object descriptors are used
 * as part of the update and remove action sentences to allow the object to be
 * updated to be described without creating the object itself.
 * 
 * <p>
 * Java class for ObjectDescriptor complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ObjectDescriptor">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:hl7-org:knowledgeartifact:r1}Expression">
 *       &lt;sequence>
 *         &lt;element name="property" type="{urn:hl7-org:knowledgeartifact:r1}PropertyExpression" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="objectType" type="{http://www.w3.org/2001/XMLSchema}QName" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ObjectDescriptor", propOrder = {
  "property"
})
public class ObjectDescriptor extends Expression {

  protected List<PropertyExpression> property;

  @XmlAttribute(name = "objectType")
  protected QName objectType;

  /**
   * Gets the value of the property property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot.
   * Therefore any modification you make to the returned list will be present
   * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
   * for the property property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
   * getProperty().add(newItem);
   * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link PropertyExpression }
   * 
   * 
   */
  public List<PropertyExpression> getProperty() {
    if (property == null) {
      property = new ArrayList<PropertyExpression>();
    }
    return this.property;
  }

  /**
   * Gets the value of the objectType property.
   * 
   * @return possible object is {@link QName }
   * 
   */
  public QName getObjectType() {
    return objectType;
  }

  /**
   * Sets the value of the objectType property.
   * 
   * @param value allowed object is {@link QName }
   * 
   */
  public void setObjectType(QName value) {
    this.objectType = value;
  }

}
