//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.26 at 04:34:23 PM PDT 
//

package org.hl7.knowledgeartifact.r1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;

/**
 * The ParameterDef type defines a parameter that can be referenced by name
 * anywhere within an expression. Parameters are defined at the artifact level,
 * and may be provided as part of the payload for an evaluation request. If no
 * parameter value is provided, the default element is used to provide the value
 * for the parameter. If no parameter or default is provided, the parameter is
 * defined to be null.
 * 
 * <p>
 * Java class for ParameterDef complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ParameterDef">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="default" type="{urn:hl7-org:knowledgeartifact:r1}Expression" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="parameterType" type="{http://www.w3.org/2001/XMLSchema}QName" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ParameterDef", propOrder = {
  "_default"
})
public class ParameterDef {

  @XmlElement(name = "default")
  protected Expression _default;

  @XmlAttribute(name = "name")
  protected String name;

  @XmlAttribute(name = "parameterType")
  protected QName parameterType;

  /**
   * Gets the value of the default property.
   * 
   * @return possible object is {@link Expression }
   * 
   */
  public Expression getDefault() {
    return _default;
  }

  /**
   * Sets the value of the default property.
   * 
   * @param value allowed object is {@link Expression }
   * 
   */
  public void setDefault(Expression value) {
    this._default = value;
  }

  /**
   * Gets the value of the name property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getName() {
    return name;
  }

  /**
   * Sets the value of the name property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setName(String value) {
    this.name = value;
  }

  /**
   * Gets the value of the parameterType property.
   * 
   * @return possible object is {@link QName }
   * 
   */
  public QName getParameterType() {
    return parameterType;
  }

  /**
   * Sets the value of the parameterType property.
   * 
   * @param value allowed object is {@link QName }
   * 
   */
  public void setParameterType(QName value) {
    this.parameterType = value;
  }

}
