//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.26 at 04:34:21 PM PDT 
//

package org.hl7.knowledgeartifact.r1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * The RealLiteral expression returns a value of type Real with the given
 * attributes.
 * 
 * <p>
 * Java class for RealLiteral complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="RealLiteral">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:hl7-org:knowledgeartifact:r1}Expression">
 *       &lt;attribute name="value" use="required" type="{urn:hl7-org:cdsdt:r2}Decimal" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RealLiteral")
public class RealLiteral extends Expression {

  @XmlAttribute(name = "value", required = true)
  protected double value;

  /**
   * Gets the value of the value property.
   * 
   */
  public double getValue() {
    return value;
  }

  /**
   * Sets the value of the value property.
   * 
   */
  public void setValue(double value) {
    this.value = value;
  }

}
