//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.26 at 04:34:05 PM PDT 
//

package org.hl7.knowledgeartifact.r1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * For a single action, specifies what level of requiredness is associated with
 * the action.
 * 
 * <p>
 * Java class for RequiredBehavior complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="RequiredBehavior">
 *   &lt;complexContent>
 *     &lt;restriction base="{urn:hl7-org:knowledgeartifact:r1}Behavior">
 *       &lt;attribute name="value" type="{urn:hl7-org:knowledgeartifact:r1}RequiredBehaviorType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RequiredBehavior")
public class RequiredBehavior extends Behavior {

}
