//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.26 at 04:34:23 PM PDT 
//

package org.hl7.knowledgeartifact.r1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * The Substring operator returns the string within stringToSub, beginning at
 * the 1-based index startIndex, and consisting of length characters.
 * 
 * If length is ommitted, the substring returned starts at startIndex and
 * continues to the end of stringToSub.
 * 
 * If stringToSub or startIndex is null, the result is null.
 * 
 * <p>
 * Java class for Substring complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Substring">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:hl7-org:knowledgeartifact:r1}Expression">
 *       &lt;sequence>
 *         &lt;element name="stringToSub" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="startIndex" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="length" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Substring", propOrder = {
    "stringToSub", "startIndex", "length"
})
public class Substring extends Expression {

  @XmlElement(required = true)
  protected Object stringToSub;

  @XmlElement(required = true)
  protected Object startIndex;

  protected Object length;

  /**
   * Gets the value of the stringToSub property.
   * 
   * @return possible object is {@link Object }
   * 
   */
  public Object getStringToSub() {
    return stringToSub;
  }

  /**
   * Sets the value of the stringToSub property.
   * 
   * @param value allowed object is {@link Object }
   * 
   */
  public void setStringToSub(Object value) {
    this.stringToSub = value;
  }

  /**
   * Gets the value of the startIndex property.
   * 
   * @return possible object is {@link Object }
   * 
   */
  public Object getStartIndex() {
    return startIndex;
  }

  /**
   * Sets the value of the startIndex property.
   * 
   * @param value allowed object is {@link Object }
   * 
   */
  public void setStartIndex(Object value) {
    this.startIndex = value;
  }

  /**
   * Gets the value of the length property.
   * 
   * @return possible object is {@link Object }
   * 
   */
  public Object getLength() {
    return length;
  }

  /**
   * Sets the value of the length property.
   * 
   * @param value allowed object is {@link Object }
   * 
   */
  public void setLength(Object value) {
    this.length = value;
  }

}
