//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.30 at 06:15:10 PM PDT 
//


package org.hl7.knowledgeartifact.r1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * The Union operator returns the union of the operands.
 * 			
 * This operator has two overloads:
 * 	List
 * 	Interval
 * 
 * For the list overload, this operator returns a list with all elements from all operands.
 * 
 * For the interval overload, this operator returns the interval that starts at the earliest starting point in the arguments, and ends at the latest starting point in the arguments. If the arguments do not overlap, this operator returns null. 
 * 
 * If any of the arguments are null, the result is null.
 * 			
 * 
 * <p>Java class for Union complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Union">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:hl7-org:knowledgeartifact:r1}NaryExpression">
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Union")
public class Union
    extends NaryExpression
{


}
