//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.26 at 04:33:55 PM PDT 
//

package org.hl7.cdsinputspecification.r2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.hl7.cdsdt.r2.CS;
import org.hl7.vmr.r2.CodedIdentifier;

/**
 * Specifies the clinical statements required regarding the evaluated person of
 * interest. Can include CodedAttributeRequirements and
 * TimeAttributeRequirements.
 * 
 * If no CodedAttributeRequirement specified, all relevant clinical statements
 * are required regardless of their coded attributes. If no
 * TimeAttributeRequirement specified, all relevant clinical statements are
 * required regardless of their time attributes. All specified
 * CodedAttributeRequirements and TimeAttributeRequirements should be fulfilled
 * in provided ClinicalStatements.
 * 
 * <p>
 * Java class for ClinicalStatementInputSpecification complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ClinicalStatementInputSpecification">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="requiredClinicalStatementTemplate" type="{urn:hl7-org:vmr:r2}CodedIdentifier" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="requiredClinicalStatementClass" type="{urn:hl7-org:cdsdt:r2}CS"/>
 *         &lt;element name="codedAttributeRequirement" type="{urn:hl7-org:cdsinputspecification:r2}CodedAttributeRequirement" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="timeAttributeRequirement" type="{urn:hl7-org:cdsinputspecification:r2}TimeAttributeRequirement" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClinicalStatementInputSpecification", propOrder = {
    "requiredClinicalStatementTemplate", "requiredClinicalStatementClass",
    "codedAttributeRequirement", "timeAttributeRequirement"
})
public class ClinicalStatementInputSpecification {

  protected List<CodedIdentifier> requiredClinicalStatementTemplate;

  @XmlElement(required = true)
  protected CS requiredClinicalStatementClass;

  protected List<CodedAttributeRequirement> codedAttributeRequirement;

  protected List<TimeAttributeRequirement> timeAttributeRequirement;

  /**
   * Gets the value of the requiredClinicalStatementTemplate property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot.
   * Therefore any modification you make to the returned list will be present
   * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
   * for the requiredClinicalStatementTemplate property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
   * getRequiredClinicalStatementTemplate().add(newItem);
   * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link CodedIdentifier }
   * 
   * 
   */
  public List<CodedIdentifier> getRequiredClinicalStatementTemplate() {
    if (requiredClinicalStatementTemplate == null) {
      requiredClinicalStatementTemplate = new ArrayList<CodedIdentifier>();
    }
    return this.requiredClinicalStatementTemplate;
  }

  /**
   * Gets the value of the requiredClinicalStatementClass property.
   * 
   * @return possible object is {@link CS }
   * 
   */
  public CS getRequiredClinicalStatementClass() {
    return requiredClinicalStatementClass;
  }

  /**
   * Sets the value of the requiredClinicalStatementClass property.
   * 
   * @param value allowed object is {@link CS }
   * 
   */
  public void setRequiredClinicalStatementClass(CS value) {
    this.requiredClinicalStatementClass = value;
  }

  /**
   * Gets the value of the codedAttributeRequirement property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot.
   * Therefore any modification you make to the returned list will be present
   * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
   * for the codedAttributeRequirement property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
   * getCodedAttributeRequirement().add(newItem);
   * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link CodedAttributeRequirement }
   * 
   * 
   */
  public List<CodedAttributeRequirement> getCodedAttributeRequirement() {
    if (codedAttributeRequirement == null) {
      codedAttributeRequirement = new ArrayList<CodedAttributeRequirement>();
    }
    return this.codedAttributeRequirement;
  }

  /**
   * Gets the value of the timeAttributeRequirement property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot.
   * Therefore any modification you make to the returned list will be present
   * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
   * for the timeAttributeRequirement property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
   * getTimeAttributeRequirement().add(newItem);
   * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link TimeAttributeRequirement }
   * 
   * 
   */
  public List<TimeAttributeRequirement> getTimeAttributeRequirement() {
    if (timeAttributeRequirement == null) {
      timeAttributeRequirement = new ArrayList<TimeAttributeRequirement>();
    }
    return this.timeAttributeRequirement;
  }

}
