//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.26 at 04:33:55 PM PDT 
//

package org.hl7.cdsinputspecification.r2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.hl7.cdsdt.r2.CS;
import org.hl7.cdsdt.r2.INT;
import org.hl7.cdsdt.r2.PQ;
import org.hl7.cdsdt.r2.RTO;

/**
 * A requirement for a time attribute of a clinical statement. Specified in
 * terms of the target time attribute and the required time interval for that
 * attribute in relationship to the index evaluation time. A
 * searchBackTimePeriod and/or a searchForwardTimePeriod must be provided.
 * 
 * <p>
 * Java class for TimeAttributeRequirement complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="TimeAttributeRequirement">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="targetTimeAttribute" type="{urn:hl7-org:cdsdt:r2}CS"/>
 *         &lt;element name="searchBackTimePeriod" type="{urn:hl7-org:cdsdt:r2}PQ" minOccurs="0"/>
 *         &lt;element name="searchForwardTimePeriod" type="{urn:hl7-org:cdsdt:r2}PQ" minOccurs="0"/>
 *         &lt;element name="mostRecentMaxCount" type="{urn:hl7-org:cdsdt:r2}INT" minOccurs="0"/>
 *         &lt;element name="maxSamplingRate" type="{urn:hl7-org:cdsdt:r2}RTO"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TimeAttributeRequirement", propOrder = {
    "targetTimeAttribute", "searchBackTimePeriod", "searchForwardTimePeriod",
    "mostRecentMaxCount", "maxSamplingRate"
})
public class TimeAttributeRequirement {

  @XmlElement(required = true)
  protected CS targetTimeAttribute;

  protected PQ searchBackTimePeriod;

  protected PQ searchForwardTimePeriod;

  protected INT mostRecentMaxCount;

  @XmlElement(required = true)
  protected RTO maxSamplingRate;

  /**
   * Gets the value of the targetTimeAttribute property.
   * 
   * @return possible object is {@link CS }
   * 
   */
  public CS getTargetTimeAttribute() {
    return targetTimeAttribute;
  }

  /**
   * Sets the value of the targetTimeAttribute property.
   * 
   * @param value allowed object is {@link CS }
   * 
   */
  public void setTargetTimeAttribute(CS value) {
    this.targetTimeAttribute = value;
  }

  /**
   * Gets the value of the searchBackTimePeriod property.
   * 
   * @return possible object is {@link PQ }
   * 
   */
  public PQ getSearchBackTimePeriod() {
    return searchBackTimePeriod;
  }

  /**
   * Sets the value of the searchBackTimePeriod property.
   * 
   * @param value allowed object is {@link PQ }
   * 
   */
  public void setSearchBackTimePeriod(PQ value) {
    this.searchBackTimePeriod = value;
  }

  /**
   * Gets the value of the searchForwardTimePeriod property.
   * 
   * @return possible object is {@link PQ }
   * 
   */
  public PQ getSearchForwardTimePeriod() {
    return searchForwardTimePeriod;
  }

  /**
   * Sets the value of the searchForwardTimePeriod property.
   * 
   * @param value allowed object is {@link PQ }
   * 
   */
  public void setSearchForwardTimePeriod(PQ value) {
    this.searchForwardTimePeriod = value;
  }

  /**
   * Gets the value of the mostRecentMaxCount property.
   * 
   * @return possible object is {@link INT }
   * 
   */
  public INT getMostRecentMaxCount() {
    return mostRecentMaxCount;
  }

  /**
   * Sets the value of the mostRecentMaxCount property.
   * 
   * @param value allowed object is {@link INT }
   * 
   */
  public void setMostRecentMaxCount(INT value) {
    this.mostRecentMaxCount = value;
  }

  /**
   * Gets the value of the maxSamplingRate property.
   * 
   * @return possible object is {@link RTO }
   * 
   */
  public RTO getMaxSamplingRate() {
    return maxSamplingRate;
  }

  /**
   * Sets the value of the maxSamplingRate property.
   * 
   * @param value allowed object is {@link RTO }
   * 
   */
  public void setMaxSamplingRate(RTO value) {
    this.maxSamplingRate = value;
  }

}
